Ticket 9
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #10
Opened 2022-07-07 07:16 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 動作テスト

## 実験方法
### 環境構築
コマンドプロンプトでpython3 とopencv をインストールする(下記のURL参照)
https://www.kkaneko.jp/tools/win/cv2.html
### 使用方法
今回作成したカメラID確認用と画像保存用のプログラムの使用方法を以下に示す。
手順１．カメラIDの確認
wslから
```
$ PowerShell.exe -ExecutionPolicy RemoteSigned -File captureCheckConnectCamera.ps1
```
を実行し、IDを確かめる。
![スクリーンショット (109)](https://user-images.githubusercontent.com/96767490/177713106-1bc2e782-5446-428f-a95d-ef7a9bf6a83e.png)

おそらくカメラID->0 はパソコンの内カメラである。
他に接続しているものがなければカメラ番号1に接続されると予想する。
手順２．画像の保存
wslから
```
$ PowerShell.exe -ExecutionPolicy RemoteSigned -File captureCameraInterface.ps1 カメラ番号
```
を実行することで画像を保存することができる。入力コマンド内の「カメラ番号」のところは手順１で確認したカメラIDを引数として与える。

## 実験結果
![course](https://user-images.githubusercontent.com/96767490/177712931-3a3661c5-e843-41bf-abe3-c4aa839a9c17.png)

2022-07-10 14:54 UTC, Takahiro55555 requested changes
モジュール(ファイル)やクラス、関数の説明をコメントではなくDocstringで記述していただけると幸いです。

モジュール(ファイル)名は、スネークケースでお願いします。
また、モジュールを配置するディレクトリ名は、中間報告の際に決めた`camera_system`に変更していただけると、他のプルリクとも統一できるかと思います。

モジュール名等の命名規則に関する参考資料: https://pep8-ja.readthedocs.io/ja/latest/#section-25

2022-07-10 14:54 UTC, Takahiro55555 commented on CameraInterface/CameraInterface.py
> +# 実行コマンド PowerShell.exe -ExecutionPolicy RemoteSigned -File captureCameraInterface.ps1 カメラ番号
pythonにおけるモジュールやクラス、関数の説明にはDocstring(`"""`等)を用いるのが一般的なようです。

また、私はDocstringのスタイルは[Google Style](https://qiita.com/11ohina017/items/118b3b42b612e527dc1d)を採用したいと考えています（異論は歓迎します）。
可能であればこの部分のみではなく、他ファイルのモジュールやClass、関数に関するDocstringをGoogle Styleに統一していただけると助かります。

2022-07-10 14:54 UTC, Takahiro55555 commented on CameraInterface/CameraInterface.py
> +    def __init__(self, cameraId):
このままでは、引数の型が分からないのでType Hintsを導入していただけると助かります。
また、上記のコメントで述べたように関数の説明にはDocstringを用いていただけると幸いです。

```suggestion
    def __init__(self, cameraId: int) -> None:
        """コンストラクタ.

        Args:
            cameraId (int): カメラ番号
        """
```

2022-07-10 14:54 UTC, Takahiro55555 commented on CameraInterface/CameraInterface.py
> +                successed, frame = camera.read()
return値を無視する場合は、`_`を使用した方が良いようです。
```suggestion
                successed, _ = camera.read()
```

参考: https://qiita.com/kiii142/items/6879cb065ad4c5f0b901#return%E5%80%A4%E3%82%92%E7%84%A1%E8%A6%96%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE_

2022-07-10 14:54 UTC, Takahiro55555 commented on CameraInterface/CheckConnectCamera.py
> +    sys.exit("カメラ番号を調べ終わりました。")
このままだと、プログラム自体が終了してしまうので、他のプログラムからこの関数を呼び出したいときに困るかも!?

```suggestion
   print("カメラ番号を調べ終わりました。")
```

2022-07-10 19:17 UTC, miyashita64 commented on CameraInterface/CameraInterface.py
> +                print("カメラ番号->", cameraNumber, "未接続")
見間違えるリスクもあるので、接続していないカメラ番号は表示しない方がいいと思います。

2022-07-10 19:17 UTC, miyashita64 commented on CameraInterface/CheckConnectCamera.py
> +    checkCameraConnection()
```suggestion
    CameraInterface.checkCameraConnection()
```

このファイルの処理はCameraInterfaceで定義されているので、それを呼び出すだけでいいと思います。

2022-07-11 05:04 UTC, kawanoichi commented
現時点でご指摘いただいた部分は修正しました。
check_connect_camera.py の実行結果を以下に示します。

![スクリーンショット (190)](https://user-images.githubusercontent.com/96767490/178192070-1020edfa-5443-482b-8934-66151a6b84b1.png)

2022-07-11 05:21 UTC, kodama0720 requested changes
course00.pngはいらないと思う
それと__pychache__もgitignoreすべき？
https://co.bsnws.net/article/300

2022-07-11 18:06 UTC, Takahiro55555 requested changes
`camera_system`ディレクトリは、Pythonのソースコードを置く場所なので、PowerShellのスクリプトファイルを置くのは適切ではないと考えます。

なので、以下のファイルはプロジェクトルートに配置したほうが良いかと考えます。
- `camera_system/capture_camera_interface.ps1`
- `camera_system/capture_check_connect_camera.ps1`

なお、これらのファイルにおける処理内容は #8 で追加した、`Makefile`で代替できるので削除してしまっても良いかもしれません。

コード中にコメントした部分の採否は、 @kawanoichi にお任せします。

2022-07-11 18:06 UTC, Takahiro55555 commented on camera_system/camera_interface.py
> +        print("Warning:コマンドライン引数にカメラIDを入力してください")
Pythonの標準ライブラリである[Argparse](https://docs.python.org/ja/3.8/howto/argparse.html)を利用したほうがスマートに書けるかもしれません(`check_connect_camera.py`もいらなくなるかも!?)。
もしも、Argparseを採用する場合、コード上部の`import sys`は削除する必要があります。
```suggestion
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("-id", "--camera-id", type=int, default=0, help="カメラ番号")
    parser.add_argument("-c", "--check-connected-camera", action="store_true", help="接続しているカメラ番号のリストを表示する")
    args = parser.parse_args()
    if args.check_connected_camera:
        CameraInterface.checkCameraConnection()
        exit(0)

    cameraInterface = CameraInterface(args.camera_id)
    cameraInterface.captureFrame()
```

以下実行例
```
PS etrobocon2022-camera-system> python .\camera_system\camera_interface.py 
画像を保存しました
PS etrobocon2022-camera-system> python .\camera_system\camera_interface.py -id 0
画像を保存しました
PS etrobocon2022-camera-system> python .\camera_system\camera_interface.py -c   
接続されているカメラの番号を調べています...

カメラ番号-> 0 接続済
カメラ番号-> 1 接続済

接続されているカメラは 2 台です。
カメラ番号を調べ終わりました。
PS etrobocon2022-camera-system> python .\camera_system\camera_interface.py -h
usage: camera_interface.py [-h] [-id CAMERA_ID] [-c]

optional arguments:
  -h, --help            show this help message and exit
  -id CAMERA_ID, --camera-id CAMERA_ID
                        カメラ番号
  -c, --check-connected-camera
                        接続しているカメラ番号のリストを表示する
```

2022-07-13 10:38 UTC, kawanoichi commented
上田さんのコードを参考に作り直しました。
ファイルはcamera_interface.pyのみで、接続カメラの確認と、画像の保存できるようになっています。

カメラIDが与えられてないときに接続されているカメラIDを表示する"
~~~
$ python camera_insterface.py
~~~
カメラから画像を取得し、保存する   
~~~
$ python camera_insterface.py -id <カメラID>
~~~


![スクリーンショット (192)](https://user-images.githubusercontent.com/96767490/178712966-71e20132-8091-4a7f-82db-630347400da0.png)

![スクリーンショット (193)](https://user-images.githubusercontent.com/96767490/178713036-51a15070-e2b6-4a61-8500-36d4efbed37f.png)

2022-07-13 10:53 UTC, Takahiro55555 approved these changes
LGTM!!!

特に、`camera_system/camera_interface.py`の`if __name__ == "__main__":`以降の部分、自分が提案したものよりも分かりやすくそして、丁寧になっていてとても良いとおもいます!!!

お疲れさまでした！

2022-07-13 12:56 UTC, kodama0720 requested changes
pep8に従うなら関数名と変数名はローワースネークケース（hoge_hoge）だと思います。

2022-07-13 13:09 UTC, kodama0720 reviewed
プルリクのFiles changedにマージされたファイルが混じってるのっていいんだっけ？

2022-07-13 13:59 UTC, mutotaka0426 commented
> プルリクのFiles changedにマージされたファイルが混じってるのっていいんだっけ？

mainをプルしたら省略されるはずだけど...
コンフリクトにならないなら大丈夫じゃない？

2022-07-14 02:27 UTC, kodama0720 approved these changes
LGTM!
お疲れ様です

2022-07-14 06:56 UTC, miyashita64 approved these changes
LGTM!!

2022-07-14 06:56 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/173919)

2022-07-14 07:10 UTC, merged