#4 PythonのCI環境を構築する
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #13
Opened 2022-07-18 00:19 UTC by Takahiro55555

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点

## 動作テスト

### 実験方法

### 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

### 実験結果

### 添付資料

2022-07-18 03:12 UTC, miyashita64 requested changes
インデントの修正をお願いします。
それと、nopepについて調べてもわからなかったので、教えていただきたいです。

2022-07-18 03:12 UTC, miyashita64 commented on camera_system/camera_interface.py
> +import cv2  # nopep8: E402
nopepで自動フォーマットを抑制している？と思うのですが、E402はコメントですか？それともこういう記法なんでしょうか？

2022-07-18 03:12 UTC, miyashita64 commented on .github/workflows/ci-python.yaml
> +          echo "https://codecov.io/gh/${GITHUB_REPOSITORY}/commit/$(git rev-parse HEAD)" >> ${GITHUB_STEP_SUMMARY}
```suggestion
          echo "## Coverage report on Codecov" >> ${GITHUB_STEP_SUMMARY}
          echo "以下のリンクから詳細を確認できます。" >> ${GITHUB_STEP_SUMMARY}
          echo "https://codecov.io/gh/${GITHUB_REPOSITORY}/commit/$(git rev-parse HEAD)" >> ${GITHUB_STEP_SUMMARY}
```

インデントがずれています。
個人的には45,46行目はインデントを減らした方が見やすいと思います。

2022-07-18 08:57 UTC, Takahiro55555 commented on .github/workflows/ci-python.yaml
> +          echo "https://codecov.io/gh/${GITHUB_REPOSITORY}/commit/$(git rev-parse HEAD)" >> ${GITHUB_STEP_SUMMARY}
私の環境で確認したところ、インデントはずれていなかったのでフォントの違い（正確には日本語フォントの横幅？）によって、GitHubのほうではずれてしまったようです。

インデントを減らしたほうが見やすいというのは、確かにそうだと思ったので提案していただいたほうを採用したいと思います。

2022-07-19 03:39 UTC, Takahiro55555 commented on camera_system/camera_interface.py
> +import cv2  # nopep8: E402
自動フォーマットではなく、pycodestyleのエラーを抑制しています。
コメントで自動フォーマットを抑制できるかはわかりません...

`E402`は、当該エラーのみを無視したく付けたのですが、ドキュメントを見る限り意味は無さそうなため消します。
また、pycodestyleのドキュメントでは`nopep8`ではなく、`noqa`が使われていたのでそちらを採用する予定です（どちらでも挙動は変わらない?）。

以下、参考資料
- [pycodestyle](https://pycodestyle.pycqa.org/en/latest/intro.html?highlight=noqa#error-codes:~:text=(%5E)%20These%20checks,for%20special%20cases.)

<!--
- [flake8](https://gitlab.com/pycqa/flake8/blob/master/README.rst#:~:text=you%20can%20ignore%20specific%20errors%20on%20a%20line%20with)
-->

2022-07-20 12:30 UTC, miyashita64 commented on camera_system/camera_interface.py
> +import cv2  # nopep8: E402
なるほど。
ご回答ありがとうございます。

2022-07-20 12:32 UTC, miyashita64 approved these changes
LGTM!!

2022-07-20 12:36 UTC, Takahiro55555 commented
> インデントの修正をお願いします。 それと、nopepについて調べてもわからなかったので、教えていただきたいです。

`nopep`関連の説明をWikiに追加しました。
https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/wiki/%5BWIP%5D%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84%E7%AD%89#pep8%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E3%82%92%E7%84%A1%E8%A6%96%E3%81%97%E3%81%9F%E3%81%84%E5%A0%B4%E5%90%88

2022-07-21 02:02 UTC, mutotaka0426 approved these changes
バッジも付いてて良いと思います！
![LGTM](https://image.lgtmoon.dev/174560)

2022-07-21 07:36 UTC, kodama0720 approved these changes
LGTM!

2022-07-21 09:14 UTC, merged