add: 座標取得GUIツールの追加
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #14
Opened 2022-07-25 01:40 UTC by mutotaka0426

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点

- 入力画像からクリックした座標を取得するGUIツールを追加

## ツールの使い方

- CoordinateGetterインスタンス生成時にGUIツールが起動する（この時ファイルのパスをコンストラクタに渡す）
- ブロック置き場８箇所，ベースサークル４箇所を順にクリックして座標を取得する
- 全ての座標を取得したらGUIツールが終了する
- CoordinateGetterインスタンスのblock_point（ブロック置き場）とbase_circle（ベースサークル）を参照することで各座標を取得できる

## 動作テスト

座標取得のデモ

https://user-images.githubusercontent.com/56989154/180675633-c0d02133-c644-43a0-b5ec-8ef8b32f591a.mp4

### 添付資料
[Pythonで画像の座標を取得する方法を現役エンジニアが解説【初心者向け】](https://techacademy.jp/magazine/51035#ta-toc-3)

2022-07-25 10:40 UTC, kawanoichi requested changes
print文の変数展開の方法に関しては好みだと思うので変更するかどうかはおまかせします．

2022-07-25 10:40 UTC, kawanoichi commented on camera_system/coordinate_getter.py
> +        """カメラシステムのコンストラクタ.
カメラシステムのコンストラクタではなく，CoordinateGetterのコンストラクタだと思います．

2022-07-25 10:40 UTC, kawanoichi commented on camera_system/coordinate_getter.py
> +                print('ブロック置き場{}：{} {}'.format(len(self.__block_point)+1, x, y))
```suggestion
                print(f'ブロック置き場{len(self.__block_point)}：{x} {y}')
```
format関数ではなくf文字列のほうが見やすいと思います．

2022-07-25 10:40 UTC, kawanoichi commented on camera_system/coordinate_getter.py
> +                print('ベースサークル{}：{} {}'.format(len(self.__base_circle)+1, x, y))
同上．
```suggestion
                print('ベースサークル{len(self.__base_circle)}：{x} {y}')
```

2022-07-25 10:44 UTC, kodama0720 requested changes
処理は問題ないと思います

2022-07-25 10:44 UTC, kodama0720 commented on camera_system/coordinate_getter.py
> +    def __showImage(self) -> None:
関数名はスネークケースでお願いします

2022-07-25 10:44 UTC, kodama0720 commented on camera_system/coordinate_getter.py
> +    def __setCoordinate(self, event, x, y, flags, params) -> None:
同上
それと引数のflagsとparamsは何ですか？

2022-07-25 10:51 UTC, kawanoichi commented
今回のチケットとは関係ないのですが，camera_interface.pyのコードで変更をお願いしたい部分が２つあります．
１つ目は7, 9, 68, 72行目の```camera_insterface.py```を```camera_interface.py```に修正をお願いします．
２つ目は69~71行にかけて```" カメラから画像を取得し、保存する\n"```を３回記述してあったので，70,71行目は消していただきたいです．
よろしくおねがいします．

2022-07-25 10:56 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +                print('ブロック置き場{}：{} {}'.format(len(self.__block_point)+1, x, y))
>print文の変数展開の方法に関しては好みだと思うので変更するかどうかはおまかせします．
この辺は、コーディング規約等で統一したほうが良さそうな気がします（正確には、文字列への変数展開？）。

```suggestion
                print('ブロック置き場%d：%d %d' % (len(self.__block_point)+1, x, y))
```
ちなみに、私は`%`演算子派です（C言語と似ているため）

また、`camera_system/camera_system.py`や`camera_system/str_to_bool.py`で既に`%`演算子を利用していることからも、`%`演算子を推したいです...

2022-07-25 11:12 UTC, mutotaka0426 commented
> 今回のチケットとは関係ないのですが，camera_interface.pyのコードで変更をお願いしたい部分が２つあります．
> 
> １つ目は7, 9, 68, 72行目の```camera_insterface.py```を```camera_interface.py```に修正をお願いします．
> 
> ２つ目は69~71行にかけて```" カメラから画像を取得し、保存する\n"```を３回記述してあったので，70,71行目は消していただきたいです．
> 
> よろしくおねがいします．

関係ないやつは別にissue立ててやった方がいいかも
小さい修正だしついでにやってしまった方が楽なのは分かるけど、後で変更を追いたい時に分かりづらくなると思う

あとは、問題(issue)に対する解決(pull request)であるべきだから、関係ないのに依存関係を持つべきではないってのもある
問題が思ってたより大きかった時とかに、リリース速度が低下するのもいただけないかな

2022-07-25 11:22 UTC, mutotaka0426 commented on camera_system/coordinate_getter.py
> +                print('ブロック置き場{}：{} {}'.format(len(self.__block_point)+1, x, y))
知らないからこの手法にしてただけで特にこだわりはないから、現行の手法に合わせようか

走行システムと並行して開発してるから、出来ればc言語に近い方がいいしね

2022-07-25 11:22 UTC, kawanoichi commented
camera_interface.pyの変更を新しいissueでやっておきます．

2022-07-25 11:25 UTC, mutotaka0426 commented
> camera_interface.pyの変更を新しいissueでやっておきます．

面倒なこと言って申し訳ないけど、よろしくお願いします

2022-07-25 12:08 UTC, Takahiro55555 requested changes
コードの変更提案部分の動作確認が出来てません。
すみません...

2022-07-25 12:08 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +        __base_circle: ベースサークルの座標リスト
>docstringは、関数などの仕様（例えば、何をして何を戻り値とするのか、呼び出すのに必要なパラメーターは何かなど）をその利用者に対して説明するために、その定義に埋め込んだ形で記述する。

とあるため、利用者から見えないプライベートな属性に関する説明は、docstringではなく単なるコメントのみで良いと思います。

参考資料: [［Python入門］docstringの書き方：Python入門 - ＠IT](https://atmarkit.itmedia.co.jp/ait/articles/1912/06/news025.html#:~:text=docstring%E3%81%AF%E3%80%81%E9%96%A2%E6%95%B0%E3%81%AA%E3%81%A9%E3%81%AE%E4%BB%95%E6%A7%98%EF%BC%88%E4%BE%8B%E3%81%88%E3%81%B0%E3%80%81%E4%BD%95%E3%82%92%E3%81%97%E3%81%A6%E4%BD%95%E3%82%92%E6%88%BB%E3%82%8A%E5%80%A4%E3%81%A8%E3%81%99%E3%82%8B%E3%81%AE%E3%81%8B%E3%80%81%E5%91%BC%E3%81%B3%E5%87%BA%E3%81%99%E3%81%AE%E3%81%AB%E5%BF%85%E8%A6%81%E3%81%AA%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E3%83%BC%E3%81%AF%E4%BD%95%E3%81%8B%E3%81%AA%E3%81%A9%EF%BC%89%E3%82%92%E3%81%9D%E3%81%AE%E5%88%A9%E7%94%A8%E8%80%85%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E8%AA%AC%E6%98%8E%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AB%E3%80%81%E3%81%9D%E3%81%AE%E5%AE%9A%E7%BE%A9%E3%81%AB%E5%9F%8B%E3%82%81%E8%BE%BC%E3%82%93%E3%81%A0%E5%BD%A2%E3%81%A7%E8%A8%98%E8%BF%B0%E3%81%99%E3%82%8B%E3%80%82)

2022-07-25 12:08 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +        self.__showImage()
コンストラクタで、画像表示と座標取得までするのは荷が重い？気がします。

以下のように、コンストラクタでメンバ変数の初期化のみを行えば、少なくともコンストラクタと`block_point`、`base_circle`のテストは可能になるかと思います。

```suggestion
    def __init__(self) -> None:
        """CoordinateGetterのコンストラクタ."""
        # メンバを初期化する.
        self.__block_point = []
        self.__base_circle = []
        self.__window_name = "Coordinate Getter"
```

2022-07-25 12:08 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +        cv2.waitKey(0)
上記のコンストラクタの代わりに、こちらの関数を呼び出すことで、座標入力画面と画像の表示を行うのはどうでしょうか？

また、このクラスを呼び出す際、画像は一旦ファイルに保存して受け渡すよりも、直接OpenCVのオブジェクトを受け渡したほうが簡潔に記述できると思います。

```suggestion
    def show_coordinate_input_window(self, img: cv2.Mat) -> None:
        """画像と座標を入力する画面を表示する関数.

        Args:
            img (cv2.Mat): 画像データ
        """
        self.__img = img
        cv2.imshow(self.__window_name, self.__img)
        cv2.setMouseCallback(self.__window_name, self.__setCoordinate)
        cv2.waitKey(0)
```

2022-07-25 12:08 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +                self.__block_point.append([x, y])
座標の値は、他のコードで間違って変更されないようにTuple型で記述するのはどうでしょうか？

```suggestion
                self.__block_point.append((x, y))
```

参考資料: [Pythonでタプルの要素を追加・変更・削除 | note.nkmk.me](https://note.nkmk.me/python-tuple-operation/#:~:text=%E6%9C%AC%E6%9D%A5%E3%80%81%E3%82%BF%E3%83%97%E3%83%AB%E3%81%AF%E6%9B%B4%E6%96%B0%E3%81%97%E3%81%9F%E3%81%8F%E3%81%AA%E3%81%84%20/%20%E3%81%95%E3%82%8C%E3%81%9F%E3%81%8F%E3%81%AA%E3%81%84%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E8%A1%A8%E7%8F%BE%E3%81%99%E3%82%8B%E3%82%82%E3%81%AE)

2022-07-25 12:08 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +                self.__base_circle.append([x, y])
座標の値は、他のコードで間違って変更されないようにTuple型で記述するのはどうでしょうか（同上）？

```suggestion
                self.__base_circle.append((x, y))
```

2022-07-25 12:08 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +    def block_point(self) -> List[int]:
Type Hintsは以下のようにしたほうが、より正確になる気がします。

```suggestion
    def block_point(self) -> List[Tuple[int, int]]:
```

上記の例は、Tuple型を採用した場合。

2022-07-25 12:08 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +    def base_circle(self) -> List[int]:
同上
```suggestion
    def base_circle(self) -> List[Tuple[int, int]]:
```

2022-07-25 12:08 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +"""座標取得GUIツール.
このモジュールの説明として、「ツール」と言ってしまうと少し、違和感があります。
モジュールの説明なので、「○○するためのモジュール.」などとしたほうが良い気がします。

2022-07-25 12:08 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +        return self.__base_circle
PRの動作確認が面倒そうだったので、以下のようにこのファイルを直接呼び出したときのみ動作確認処理を呼び出すようにしても良いかもしれません。

```suggestion
        return self.__base_circle

if __name__ == "__main__":
    img = cv2.imread("../tests/data/course.png")
    coord = CoordinateGetter()
    coord.show_coordinate_input_window(img)
    print("ブロック置き場: %s" % coord.block_point)
    print("ベースサークル: %s" % coord.base_circle)
```

2022-07-25 12:19 UTC, Takahiro55555 commented on camera_system/coordinate_getter.py
> +        cv2.waitKey(0)
画像データはコンストラクタで渡してしまっても良い気がしてきました。

2022-07-25 16:56 UTC, mutotaka0426 commented on camera_system/coordinate_getter.py
> +        cv2.waitKey(0)
引数として渡すのは画像データよりもファイルパスの方がよくない？
呼び出し元でもopenCVを扱うより，CoordinateGetterの方でopenCV関連の処理を一任した方がよくない？

2022-07-25 17:02 UTC, mutotaka0426 commented on camera_system/coordinate_getter.py
> +        return self.__base_circle
モジュール内に動作確認用の処理も記述するのが一般的なの？
PRのはインスタンス生成後にゲッターで座標を取得できることを確認したかったから，ちょっと面倒なことしてたけど

一応カメラシステムとは独立して動かすこともできるツールだから，単純に動作確認用ってわけでもないかもしれないけど

2022-07-25 19:23 UTC, mutotaka0426 commented on camera_system/coordinate_getter.py
> +        cv2.waitKey(0)
一つの画像に対して一つのCoordinateGetterインスタンスであるべきな気がしてきた．

指摘通りコンストラクタとウィンドウ表示は分けるとして，コンストラクタにファイルパスは渡すのはどう？

2022-07-27 16:08 UTC, kawanoichi commented
動作は確認できました。(```pip install pillow``` は必要でした。)
ボーナスブロックは考慮しなくていいのでしょうか...？

2022-07-27 16:09 UTC, mutotaka0426 commented
> 動作は確認できました。(`pip install pillow` は必要でした。) ボーナスブロックは考慮しなくていいのでしょうか...？

2022-07-27 16:35 UTC, Takahiro55555 commented
@mutotaka0426  @kawanoichi 
> 動作は確認できました。(`pip install pillow` は必要でした。) ボーナスブロックは考慮しなくていいのでしょうか...？

`pip`ではなく、`poetry add pillow`のようにパッケージを追加する必要があります。
その後、変更された`poetry.toml`と`poetry.lock`をコミットしてください。

動作確認する人は、手元で`git pull`した後`poetry install`コマンドを実行してください。

2022-07-27 16:42 UTC, kawanoichi commented on camera_system/camera_coordinate_calibrator.py
> +    print("ベースサークル: %s" % coord.end_point)
```suggestion
    print("端点サークル: %s" % coord.end_point)
```

2022-07-27 16:46 UTC, kawanoichi requested changes
コメントでピリオドがある場所とない場所があるので統一をお願いします。

2022-07-27 16:48 UTC, kawanoichi commented
> コメントでピリオドがある場所とない場所があるので統一をお願いします。

2022-07-27 16:51 UTC, mutotaka0426 commented
> コメントでピリオドがある場所とない場所があるので統一をお願いします。

ピリオドがある場所って関数名やクラスの説明のところのこと？
多分ここはピリオドを入れないとlintで引っかかるっぽい？

2022-07-27 16:53 UTC, mutotaka0426 commented
> > コメントでピリオドがある場所とない場所があるので統一をお願いします。
> 
> ピリオドがある場所って関数名やクラスの説明のところのこと？ 多分ここはピリオドを入れないとlintで引っかかるっぽい？

他にもありましたね．失礼しました

2022-07-27 16:54 UTC, kawanoichi commented on camera_system/camera_coordinate_calibrator.py
> +        img_width = self.__img.shape[1]
```self.__img.shape[0]```を41行目で使用しているので、41行目より前に定義し、```img_height```を使用すべきかと思います...
```img_width```も同様にお願いします。

2022-07-27 16:54 UTC, kawanoichi commented on camera_system/camera_coordinate_calibrator.py
> +    print("ベースサークル: %s" % coord.end_point)
```suggestion
    print("端点サークル: %s" % coord.end_point)
```
変更お願いします。

2022-07-27 16:54 UTC, kawanoichi requested changes
変更お願いします。

2022-07-27 21:36 UTC, Takahiro55555 requested changes
可能であれば、テストコードもPushしていただけると幸いです。

2022-07-27 21:36 UTC, Takahiro55555 commented on camera_system/camera_coordinate_calibrator.py
> +            List[int]: ブロック置き場の座標リスト ([x座標, y座標]の形で格納)
```suggestion
            List[Tuple[int, int]]: ブロック置き場の座標リスト ([x座標, y座標]の形で格納)
```

2022-07-27 21:36 UTC, Takahiro55555 commented on camera_system/camera_coordinate_calibrator.py
> +            List[int]: ベースサークルの座標リスト ([x座標, y座標]の形で格納)
```suggestion
            List[Tuple[int, int]]: ベースサークルの座標リスト ([x座標, y座標]の形で格納)
```

2022-07-27 21:36 UTC, Takahiro55555 commented on camera_system/camera_coordinate_calibrator.py
> +            List[int]: 端点サークルの座標リスト ([x座標, y座標]の形で格納)
```suggestion
            List[Tuple[int, int]]: 端点サークルの座標リスト ([x座標, y座標]の形で格納)
```

2022-07-27 21:36 UTC, Takahiro55555 commented on camera_system/camera_coordinate_calibrator.py
> +        self.__base_circle = []
`__end_point `もリセットしたほうが良い?
```suggestion
        # リストをリセットする
        self.__block_point = []
        self.__base_circle = []
        self.__end_point = []
```

2022-07-28 04:00 UTC, kawanoichi approved these changes
LGTM!!

2022-07-28 06:28 UTC, Takahiro55555 requested changes
ご確認いただけると幸いです。

2022-07-28 06:28 UTC, Takahiro55555 commented on camera_system/camera_coordinate_calibrator.py
> +            event: イベント
引数名以上の情報を説明には付けたほうが良い気がしてきた（今更すみません...）
```suggestion
            event: マウスイベント
```

2022-07-28 06:28 UTC, Takahiro55555 commented on camera_system/camera_coordinate_calibrator.py
> +            event: イベント
```suggestion
            event: リセットボタンのクリックイベント
```

2022-07-28 06:34 UTC, Takahiro55555 reviewed
LGTM!!!

2022-07-28 06:34 UTC, Takahiro55555 approved these changes

2022-07-28 10:26 UTC, kodama0720 approved these changes
LGTM!

2022-07-28 10:30 UTC, merged