close #19 ColorChangerクラスのバグ調査と修正
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #20
Opened 2022-08-14 10:12 UTC by kawanoichi

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
バグの解決はできませんでした．なのでライブラリ使うのやめ，for文で書き直しました．

### コース画像
![base_circle1](https://user-images.githubusercontent.com/96767490/184531779-5a9dc449-c2f8-4f05-9ebd-afd5ecd070a5.png)
[course_images.zip](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/files/9333016/course_images.zip)

### 修正前ファイルを使用した６色変換画像
![result_base_circle1](https://user-images.githubusercontent.com/96767490/184531870-7c4de344-feb4-449a-94b7-a4a8725ec189.png)

### 修正後ファイルを使用した６色変換画像
１枚の画像に対する処理時間は約2.7秒です．
![base_circle1](https://user-images.githubusercontent.com/96767490/184531795-c82d2927-2c5e-4ed4-ad3e-d6edfaab7e18.png)
[results.zip](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/files/9333017/results.zip)

修正後ファイルではうまく6色変換できていると思います（主観）．
## バグ調査の結果で分かったこと

実験ではコース画像上の赤ブロック部分を切り抜いた画像を使用しています．
修正前ファイルはライブラリを使用して6色変換を行い，修正後ファイルはライブラリではなくfor文で6色変換を行っています．
実験1,2,3での閾値の設定は```__Upper```で設定している値を含むかどうかを変更しています．
ライブラリでは```>=```と```>```の変更ができないため直接```__Upper```の値を変更して実験を行いました．

### 実験１
修正前ファイル
閾値 ```__Lower```以上 かつ ```__Upper```より小さい(```__Upper```以下でも結果は同じ)
![test_result_old](https://user-images.githubusercontent.com/96767490/184531042-8ecb826a-1f18-4ca6-a651-f1373f128e1c.png)

### 実験２
修正後ファイル
閾値 ```__Lower```以上 かつ ```__Upper```より小さい
![test_result_new](https://user-images.githubusercontent.com/96767490/184531092-048e611d-7375-40e2-9499-a2ca7b52360e.png)

### 実験３
修正後ファイル
閾値 ```__Lower```以上 かつ ```__Upper```以下
![test_result_new](https://user-images.githubusercontent.com/96767490/184531040-8b4056c8-cc59-4d20-8700-8e07adfff759.png)

修正後ファイルを使用した実験から閾値の__Upperで256を含まない場合に修正前ファイルと同じようなバグが発生しました．
しかし，修正前ファイルの閾値の上限を上げてもバグは消えませんでした．
実験から修正前ファイルの```cv.bitwise_and```関数でバグが発生していると考えます．(解決はできませんでした)

2022-08-15 08:04 UTC, kodama0720 requested changes
見た感じ黒のノイズが無くなっていていいと思います。
フォーマットのチェックが通っていないので修正をお願いします。

2022-08-15 08:04 UTC, kodama0720 commented on camera_system/color_changer.py
> +    def change_color(self, path: str, save_path: str) -> None:
書き込むファイルをsave_pathにするなら、読み込むファイルもread_pathとかの方がいいと思います。

2022-08-15 20:20 UTC, mutotaka0426 requested changes
6色変換自体は改善されてるみたいだからいいと思う！
可読性を意識したコードを書いてくれるとレビューがしやすくなるから，コメントや変数名などに気を使って書いてほしい

気になったんだけど，6色変換に約2.7秒かかるって書いてるけど，もともとはどれくらいかかってたの？
ライントレースエリアの走行時間が大体10秒くらいって考えると，2.7秒は割と重いけど仕方ないのかな

2022-08-15 20:20 UTC, mutotaka0426 commented on camera_system/color_changer.py
> +        color_ids = [0,0,1,2,3,4]
color_idsの説明はコメントとして書いてほしい
`LOWER[0]≦cell≦UPPER[0]`or`LOWER[1]≦cell≦UPPER[1]`のときに赤に変換する？ってことなんだろうけど，読み解くのに時間がかかって不親切だと思う

2022-08-15 20:20 UTC, mutotaka0426 commented on camera_system/color_changer.py
> +            # TrueなindexにBGRを代入
処理的には代入なんだけど，置換するって書いた方が意味が分かりやすいかも？
```suggestion
            # Trueなindexの値を6色値に置換
```

2022-08-16 09:16 UTC, kawanoichi commented
元のファイル(ライブラリを使用)での実行時間は0.07秒でした。

2022-08-17 11:16 UTC, miyashita64 commented on camera_system/color_changer.py
> +            result[np.where(mask)] = ColorChanger.__BGR_COLOR[color_ids[i]]
もっと綺麗な書き方がある気がしますが、以下の処理にすると自分の環境では0.23sほどで実行できました。
```suggestion
            # 条件に対するbool値を代入
            mask = np.array([np.all(ColorChanger.__LOWER[i] <= hsv, axis=1), np.all(hsv <= ColorChanger.__UPPER[i], axis=1)])
            mask2 = np.all(mask.T, axis=1)
            # Trueなindexの値をBGRに置換
            result[np.where(mask2)] = ColorChanger.__BGR_COLOR[color_ids[i]]
```

2022-08-17 17:34 UTC, kawanoichi commented on camera_system/color_changer.py
> +            result[np.where(mask)] = ColorChanger.__BGR_COLOR[color_ids[i]]
処理時間は宮下君と変わらないのですがこの書き方はきれいですか？
```
for i in range(len(color_ids)):
    # 条件に対するindexをBGR変換
    result[np.where(np.all(ColorChanger.__LOWER[i] <= hsv, axis=1) & np.all(hsv <= ColorChanger.__UPPER[i], axis=1),True,False)] = ColorChanger.__BGR_COLOR[color_ids[i]]
```

2022-08-17 17:58 UTC, kawanoichi commented on camera_system/color_changer.py
> +            result[np.where(mask)] = ColorChanger.__BGR_COLOR[color_ids[i]]
長いからこっちのほうがいいかな？
```
for i in range(len(color_ids)):
    # 条件に対するindexを取得
    index = np.where(np.all(ColorChanger.__LOWER[i] <= hsv, axis=1) & np.all(hsv <= ColorChanger.__UPPER[i], axis=1))
    # BGRに変換
    result[index] = ColorChanger.__BGR_COLOR[color_ids[i]]

```

2022-08-18 03:05 UTC, kawanoichi commented
新しくpushしたのでレビューお願いします。
僕のPCだと実行時間は0.1sでした。

2022-08-18 04:08 UTC, kodama0720 approved these changes
LGTM!

2022-08-18 04:43 UTC, sugaken0528 approved these changes
LGTM

2022-08-18 04:56 UTC, miyashita64 approved these changes
LGTM!!

2022-08-19 05:05 UTC, mutotaka0426 commented
# TODOリスト
- 画像保存じゃなくてメンバに画像データを保持しておく形に変更する
- 画像データのゲッタを作る

2022-08-25 07:01 UTC, mutotaka0426 approved these changes

2022-08-25 07:02 UTC, merged