close #21 スタート関数を追加する
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #25
Opened 2022-08-25 08:06 UTC by miyashita64

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- camera_system.pyに計画を開始するstart()を作成
- __main__.pyにCameraSystemのstart()を実行する処理を追加

## 動作テスト
makeで実行できることを確認した

### 添付資料

2022-08-25 08:29 UTC, Takahiro55555 requested changes

2022-08-25 08:29 UTC, Takahiro55555 commented on camera_system/camera_system.py
> +    def start(self):
戻り値は無い想定？
```suggestion
    def start(self) -> None:
```

2022-08-25 08:29 UTC, Takahiro55555 commented on camera_system/camera_system.py
> +        # コマンドファイルを送信(システム外)
コメントの先頭に`ToDo`を付けたら検索機能で簡単に探すことができるので、実装忘れが無いか探しやすくなると思います。
```suggestion
        # ToDo: 通信を確立する

        # ToDo: キャリブレーション

        # ToDo: 開始合図を受け取るまで待機

        # ToDo: ゲームエリア情報を生成する

        # ToDo: 計画する

        # ToDo: コマンドファイルを生成

        # ToDo: コマンドファイルを送信(システム外)
```

2022-08-25 08:46 UTC, Takahiro55555 approved these changes
LGTM!!!

素早いプルリクありがとうございます。

2022-08-25 10:12 UTC, KakinokiKanta approved these changes
LGTM!

2022-08-25 15:21 UTC, mutotaka0426 approved these changes
素晴らしい！
![LGTM](https://image.lgtmoon.dev/178716)

2022-08-26 02:15 UTC, Takahiro55555 approved these changes

2022-08-26 02:15 UTC, merged