close #22 走行システムから競技開始合図を受け取る
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #26
Opened 2022-08-30 10:08 UTC by miyashita64

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
- 走行システムから競技開始合図を受け取るまで待機する処理を追加

## 動作テスト
### 実験方法
カメラシステムへ競技開始合図を送り、カメラシステムがそれを受信していることを確認する。

### 実験データ
https://user-images.githubusercontent.com/83441177/187383522-575b8f44-83ed-431d-8583-cc70637f384e.MOV

### 実験結果
競技開始をカメラシステムに合図できた。

### 参考資料
[Python ソケット通信のサンプル](https://itsakura.com/python-socket)
[Pythonでunittestを行うとき、参照パスがずれる問題](https://qiita.com/TakamiChie/items/9d576b6718e866ef21ab)

2022-08-31 11:32 UTC, kodama0720 approved these changes
LGTM !

2022-08-31 13:12 UTC, kawanoichi requested changes
サーバとサーバーの統一お願いします
それ以外はいいと思います。

2022-08-31 16:26 UTC, mutotaka0426 approved these changes
見やすくてきれいなコードだと思う！
@kawanoichi が指摘した点以外は特に気にならなかった
LGTM!
![LGTM](https://image.lgtmoon.dev/127780)

2022-09-01 02:10 UTC, sugaken0528 requested changes
少し疑問に思ったところがあるので回答お願いします

2022-09-01 02:10 UTC, sugaken0528 commented on camera_system/client.py
> +                print("Unconnected.")
```suggestion
            except ConnectionError as e:
                # 接続できなかった場合
                print("{}: {}".format(type(e).__name__, str(e)))
```
全然詳しくはないけど接続エラーの原因って何かわかるようにしてた方がいいんじゃないの？
それと接続エラーが起きた時ってbreakした方が良いんじゃない？

2022-09-01 04:16 UTC, miyashita64 commented on camera_system/client.py
> +                print("Unconnected.")
エラー文は修正します。
接続エラーでbreakしてしまうと、開始合図を受け取る前(ブロックが並べられる前)に計画を始めてしまい、おかしな経路を作ってしまうと思うので、そうなるよりは無限ループのままのほうがいいと思います。

2022-09-01 04:20 UTC, sugaken0528 approved these changes
LGTM

2022-09-01 04:39 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-09-01 05:50 UTC, kawanoichi approved these changes
LGTM

2022-09-01 05:50 UTC, merged