close #21 画像からブロックの色取得とゲームエリア情報の実装
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #27
Opened 2022-08-30 21:32 UTC by kawanoichi

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
CameraCalibrationクラスは以下の関数を保持するクラス
- カメラキャリブレーション(GUIから座標取得)関数
- コース情報を作成する(ブロックに対するカラーIDをGameInfoクラス変数に渡す)関数

ColorChangerクラスの変更点
- 色クラスをEnumのサブクラスとして使用する(使い方は添付資料を参照)
- ６色変換クラスで最頻値を求めるために色idの配列を新たに作成(70,71行目)
- CameraCalibrationクラスで定義した領域内で色の最頻値を求める関数を追加

GameInfoクラスは以下の関数を保持するクラス
- 運搬していないブロックがあるブロック置き場を取得する関数
- 走行禁止座標を取得する関数
- 回頭禁止方向を取得する関数
### 添付資料
列挙型クラス Enumの使用方法
https://docs.python.org/ja/3/library/enum.html
```
from enum import Enum

class Color(Enum):
    RED = 0
    BLUE = 1

print(Color.RED.value)
>>> 0
print(Color.RED.name)
>>> RED
print(Color(0).value)
>>> 0
print(Color(0).name)
>>> RED
print(Color(1).value)
>>> 1
print(Color(1).name)
>>> BLUE
```

2022-08-31 13:15 UTC, miyashita64 requested changes
型とコメントについて気になったので対応よろしくお願いします。

2022-08-31 13:15 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +    def camera_calibration_start(self):
startはなくていい気がします。

2022-08-31 13:15 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +        end_id = []
コメントと処理が合ってないと思います

2022-08-31 13:15 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +    def __init__(self, read_path):
```suggestion
    def __init__(self, read_path: str):
```
型指定をお願いします

2022-08-31 13:15 UTC, miyashita64 commented on camera_system/camera_coordinate_calibrator.py
authorを追記してください。
(上部にコメントできないのでここに書いてます)

2022-08-31 13:15 UTC, miyashita64 commented on camera_system/color_changer.py
> +    def change_color(self, img, save_path) -> None:
型をお願いします

2022-08-31 13:15 UTC, miyashita64 commented on camera_system/game_info.py
> +    }
ノードはNodeクラスで表現すると思ってましたが、辞書でしますか？ノードの種類（中点、交点、ブロック置き場）や交点の色など、座標から計算はできますが、メンバとして情報を持っている方がわかりやすいと思います。
それとキーがタプルなのは個人的に違和感があります。

2022-08-31 13:15 UTC, miyashita64 commented on camera_system/game_info.py
> +        base_color_dict (Dict{int, str}): ベースエリアの色ID(赤、黄、緑、青)
```suggestion
        base_color_list (List[Color]): ベースエリアの色ID(赤、黄、緑、青)
```
ですか？

2022-08-31 13:25 UTC, miyashita64 reviewed
すみません。追加で見つかりました。
対応お願いします。

全体的に、色id系はColorで統一した方がいいと思います。

2022-08-31 13:25 UTC, miyashita64 commented on camera_system/robot.py
> +    direct = Direction.N.value
計画では複数パターンの走行体を考えると思うので、インスタンス変数で持つ方がいいと思います

2022-08-31 17:32 UTC, mutotaka0426 requested changes
色々指摘してるので，対応お願いします

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +from color_changer import ColorChanger
まとめられなかったっけ
```suggestion
from color_changer import Color, ColorChanger
```

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +        """コース情報作成を行う関数."""
ゲーム（エリア？）情報なのかコース情報なのかは統一した方がいいと思う 

モデルに合わせるならゲームエリア情報だから，以下のようにすればいいかな
```suggestion
    def make_game_area_info(self):
        """ゲームエリア情報作成を行う関数."""
```
この場合`GameInfo`の方も`GameAreaInfo`にするべきだけど...

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +        self.__img = cv2.imread(read_path)
前に誰かと話した気がするけど，ファイルって保存する必要ってあるかな？
確認できるって点では意味があるかもしれないけど，CameraInterfaceから直接画像データひっぱてく方がよくない？

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/camera_coordinate_calibrator.py
> +    def __init__(self) -> None:
この変更の意図がよく分からないだけど，なんで関数で指定するようにしたの？

一つの画像に対して一つのCameraCoordinateCalibratorインスタンスであるべきだと思うんだけど，これだと別のファイルを指定すれば座標を書き換えることが可能になってしまってよくないと思う

2022-08-31 17:32 UTC, mutotaka0426 commented on tests/test_color_changer.py
> +        mode01 = cc.mode_color(132, 150, 5, 5)  # ブロック置き場1
アサーションは`expected`と`actual`の対比であるべきだから，`mode01`とかじゃなくて`actual`にするべき
```suggestion
        actual = []
        actual.append(cc.mode_color(132, 150, 5, 5))  # ブロック置き場1
```
これなら，アサーションもfor文でまとめられるんじゃない

2022-08-31 17:32 UTC, mutotaka0426 commented on tests/test_color_changer.py
> +        self.assertEqual(True, actual_exist)
直接書き込むのはよくないから，`expected_exist`みたいなのを用意した方がいい
```suggestion
        self.assertEqual(expected_exist, actual_exist)
```
変数名的に，ここはファイルが存在してることの確認だよね？
19~27行らへんはもう少しコメントが欲しいかも

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +        self.__img = cv2.imread(read_path)
て思ったけど，画像保存がタイムロスにならないなら保存した方が保守性あるし，CameraSystem.start()内で画像を保存してキャリブレーションって流れの方がいいか？
だとしたらこのままでいいや

皆の意見求む

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +    def camera_calibration_start(self):
`start_camera_calibration`とかじゃない？
```suggestion
    def start_camera_calibration(self):
```

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +    save_path = "result_" + read_path
ただの動作確認だからどうでもいいけど，`save_path`はなくていいんじゃない？

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +        self.__save_path = "result_" + read_path
変数名は`__save_path`でもいいと思うけど，コメントで6色画像のパスみたいな説明を入れた方がいいかも？

あとファイル名result_じゃなくて，color_とかの方が分かりやすくない？

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +        self.__color_changer.change_color(self.__img, self.__save_path)
ゲームエリア情報を作成するときに，使う画像は`self.__img`じゃない

`camera_calibration_start()`で使う画像はキャリブレーション時の画像で，
`make_game_info()`で使う画像は競技が開始してから取得する画像だよ

2022-08-31 17:32 UTC, mutotaka0426 commented on camera_system/color_changer.py
> +    def mode_color(self, coord_x: int, coord_y: int,
カメラシステムの方だと明確に定義してない？けど，関数名は動詞(+名詞)の形の方がいいと思う
だから，`calculate_mode_color()`とか？

2022-08-31 19:55 UTC, kawanoichi commented on camera_system/camera_calibrator.py
> +        self.__img = cv2.imread(read_path)
個人的にはタイムロスにならないのであれば保存すべきではないかと思います。仮に本番うまくいかなかった場合などにcolor_changerファイルに問題があるかなど確認しやすいので...

2022-08-31 20:11 UTC, kawanoichi commented on camera_system/camera_calibrator.py
> +    def camera_calibration_start(self):
startいらないという意見もありますがどちらがいいでしょうか？

2022-08-31 20:15 UTC, kawanoichi commented on camera_system/camera_calibrator.py
> +        self.__save_path = "result_" + read_path
color_save_pathはなんか違う気がするのでsが、changed_save_pathはどうですか？

2022-08-31 20:16 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +    def camera_calibration_start(self):
startがどうっていうよりは，関数名は動詞(+名詞)の形にした方がいいと思う
候補としては，
- `start_camera_calibration()`
- `start()`
- `run_camera_calibration()`
- `run()`
- `calibrate()`

とかか？
`start_camera_calibration()`でいいと思うけど

2022-08-31 20:18 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +        self.__save_path = "result_" + read_path
変数名の話？変数名はそのままでもいいんじゃない？

保存するときのファイル名をcolor_にした方がいいんじゃないってこと

2022-08-31 20:30 UTC, kawanoichi commented on camera_system/camera_calibrator.py
> +        self.__color_changer.change_color(self.__img, self.__save_path)
本番のコース画像は関数の引数でうけとることにしましたが、いい名前がおもいつきません。とりいえずactual_cource_imgにしました。いい名前ありますか？

2022-08-31 21:26 UTC, kawanoichi commented
すみません。見直したら最頻値を求める際に白と黒を消去した後、空配列になってし待った場合の処理を書いていなかったので空配列だった場合赤のカラーIDを返す処理をついかしました。

2022-08-31 23:47 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +class CameraCalibration:
ファイル名や他クラスと合わせるなら、
```suggestion
class CameraCalibrator:
```

2022-09-01 10:33 UTC, mutotaka0426 requested changes
修正が確認できたやつは`Resolve conversation`しました

追加で修正お願いします

2022-09-01 10:33 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +        self.__calibration_img = cv2.imread(read_path)
やっぱり，これをCameraInterfaceで直接取得するようにした方がいいと思う
同じシステム内なのにファイルを介してやり取りするっておかしくない？

だからCameraInterface.capture_frame()の戻り値に`cv2.imread(frame)`にして，ここで呼び出すべきだと思う
```suggestion
        self.__calibration_img = camera_interface.capture_frame()
```

2022-09-01 10:33 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +    def make_game_area_info(self, game_area_img: cv2.Mat) -> None:
ここも引数として画像データを受け取るんじゃなくて，`make_game_area_info()`内でCameraInterface.capture_frame()を使って画像データを取得するべきだと思う

2022-09-01 10:33 UTC, mutotaka0426 commented on camera_system/game_info.py
> +class GameInfo:
ファイル名，クラス名，インスタンス名とか諸々，GameAreaInfoとかgame_area_infoに統一しよう
```suggestion
class GameAreaInfo:
```

2022-09-01 10:33 UTC, mutotaka0426 commented on camera_system/camera_system.py
> +        # コース情報の作成
```suggestion
        # ゲームエリア情報の作成
```

2022-09-01 10:33 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +        """コース情報作成を行う関数."""
```suggestion
        """ゲームエリア情報作成を行う関数."""
```

2022-09-01 10:33 UTC, mutotaka0426 commented on camera_system/camera_calibrator.py
> +        # コース情報を作成
```suggestion
        # ゲームエリア情報を作成
```

2022-09-02 05:56 UTC, miyashita64 requested changes
レビュー遅くなってすみません。
対応よろしくお願いします。

2022-09-02 05:56 UTC, miyashita64 commented on camera_system/camera_system.py
>          # ToDo: キャリブレーションする(ゲームエリア情報).
ToDoは完了したら消してください

2022-09-02 05:56 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +        return self.__calibration_img
どこかで使ってる？

2022-09-02 05:56 UTC, miyashita64 commented on camera_system/game_area_info.py
> +    def get_no_entry_coordinate(robot) -> List[Node]:
```suggestion
    def get_no_entry_coordinate(robot) -> List[Coordinate]:
```

2022-09-02 05:56 UTC, miyashita64 commented on camera_system/game_area_info.py
> +        """
```suggestion
    def get_no_rotate_direction(robot) -> List[Direction]:
        """回頭禁止方向を取得する関数.

        Args:
            robot: 仮想走行体

        Returns:
            List[Direction]: 回頭禁止方向の方位リスト
        """
```

2022-09-02 05:56 UTC, miyashita64 commented on camera_system/game_area_info.py
> +        Node(-1, Coordinate(6, 1), __cross),
```suggestion
        Node(-1, Coordinate(0, 1), __middle), Node(0, Coordinate(1, 1), __block_storage),
        Node(-1, Coordinate(2, 1), __middle), Node(1, Coordinate(3, 1), __block_storage),
        Node(-1, Coordinate(4, 1), __middle), Node(2, Coordinate(5, 1), __block_storage),
        Node(-1, Coordinate(6, 1), __middle),
```

かな？
入力ミスも考えると、Node側で座標からノードの種類を求める方がいいと思います。

2022-09-02 08:28 UTC, mutotaka0426 requested changes
良い感じだと思う
小さい修正だけあるので対応よろしく

あと，修正漏れがあるから，それもよろしく
https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/pull/27/files#r959822600

2022-09-02 08:28 UTC, mutotaka0426 commented on camera_system/camera_interface.py
>          """カメラから画像を取得、保存."""
```suggestion
    def capture_frame(self, save_path: str) -> cv2.Mat:
        """カメラから画像を取得、保存.
        
        Args:
            save_path: 画像保存のパス
            
        Returns:
            cv2.Mat: 画像データ
        """
```

2022-09-02 08:28 UTC, mutotaka0426 commented on camera_system/camera_system.py
>          """ゲーム攻略を計画する."""
```suggestion
        """ゲーム攻略を計画する.
        
        Args:
            camera_id: カメラ番号
        """
```

2022-09-02 08:28 UTC, mutotaka0426 commented on camera_system/camera_system.py
> +        camera_calibrator.make_game_area_info()
コンフリクト解消するときにどのみちやると思うけど，ここは「開始合図を受け取るまで待機する」の後ね

2022-09-02 10:23 UTC, mutotaka0426 approved these changes
お疲れ様！
コンフリクトの解消だけよろしく

![LGTM](https://image.lgtmoon.dev/179848)

2022-09-02 10:49 UTC, miyashita64 approved these changes
お疲れ様です！
![LGTM](https://image.lgtmoon.dev/179855)

2022-09-03 04:38 UTC, KakinokiKanta approved these changes
LGTM!

2022-09-03 07:14 UTC, mutotaka0426 commented on camera_system/camera_system.py
> +        os.mkdir("command_files")
os.makedirs()の方がいいかも？これなら既にファイルがあっても大丈夫なはず
[参考](https://note.nkmk.me/python-os-mkdir-makedirs/)
```suggestion
        os.makedirs("command_files")
```

2022-09-03 07:16 UTC, mutotaka0426 commented on camera_system/camera_system.py
> +        os.mkdir("command_files")
これなら大丈夫かな？
[参考](https://note.nkmk.me/python-os-mkdir-makedirs/)
```suggestion
        os.makedirs("command_files", exist_ok=True)
```

2022-09-03 09:13 UTC, merged