add: ゲーム動作クラス及びゲーム動作のInvoker役となるクラスの追加
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #28
Opened 2022-08-31 07:22 UTC by mutotaka0426

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- 8つのゲーム動作をCommandパターンで実装
- ゲーム動作のInvoker役となるCompositeGameMotionクラスの追加
- CameraSystem.start()に，ゲーム動作リストから生成したコマンドが記述される，`GameAreaLeft.csv`と`GameAreaRight.csv`を生成する処理を追加

## 動作テスト
`make run-L`及び`make run-R`を実行したとき，それぞれ`GameAreaLeft.csv`と`GameAreaRight.csv`が生成されることを確認した

## 参考資料
[Pythonで、デザインパターン「Command」を学ぶ - Qiita](https://qiita.com/ttsubo/items/428a6241bd6b2562826a)

2022-08-31 11:27 UTC, miyashita64 reviewed
お疲れ様です。全体的にわかりやすいと思います。

少し気になったのが、縦調整の
```
command_list += "DS,10,70\n"
```
や回答判定の
```
if self.__angle != 0:  # 回頭角度が0の場合はコマンドは生成しない
   # 回頭角度が正の数の場合時計回り，負の数の場合反時計回りで回頭をセットする
   clockwise = "clockwise" if self.__angle > 0 else "anticlockwise"
   command_list += "RT,%d,%d,%s\n" % (abs(self.angle), GameMotion.ROTATION_PWM, clockwise)
```
など、パラメータや処理手順が同じ処理は、GameMotionが持っていてもいいと思いました。ただ、各ゲーム動作毎に縦調整などを変えたいこともあるかもしれないので、現状のままでもいいと思います。

2022-08-31 16:17 UTC, mutotaka0426 commented
> など、パラメータや処理手順が同じ処理は、GameMotionが持っていてもいいと思いました。ただ、各ゲーム動作毎に縦調整などを変えたいこともあるかもしれないので、現状のままでもいいと思います。

そうだね．
想定の上では同じ動作だけど，ゲーム動作毎に少し調整してもいいとは思うし，各ゲーム動作毎に書いた方がいいんじゃないかな．

2022-08-31 19:45 UTC, kawanoichi commented on camera_system/composite_game_motion.py
> +            commands += game_motion.generate_command()
すいません、まだ全部見れてないですが気になったところをコメントさせていただきます。
僕の理解不足かもしれないですが、これはcommandsの中のcommandごとの区切りは生成されるのでしょうか？
commandsの区切り(コンマ？)は必要ないですか？

2022-08-31 20:06 UTC, mutotaka0426 commented on camera_system/composite_game_motion.py
> +            commands += game_motion.generate_command()
commandごとの区切りってどれのことを言ってるのかが分からないけど，
33行目の`game.motion.generate_command()`で以下の例のような文字列が生成されるよ．
```
RT,225,100,clockwise,中点→交点\n
EC,right\n
CL,BLUE,0,60,0.1,0.08,0.08\n
DS,20,60\n
```
これをfor文で繰り返して，`__game_motion_list`の全部のコマンドを生成してる

2022-08-31 22:02 UTC, kodama0720 requested changes
見た感じよさそうです
いくつかコメントの修正をお願いします

2022-08-31 22:02 UTC, kodama0720 commented on camera_system/game_motion.py
> +    ttributes:
```suggestion
    attributes:
```

2022-08-31 22:02 UTC, kodama0720 commented on camera_system/composite_game_motion.py
> +ゲーム動作のリストからコマンド生成やコスト計算をする
合ってますか？

2022-09-01 03:16 UTC, KakinokiKanta requested changes
レビュー遅くなってしまい申し訳ありません。復帰動作のパラメータについてですが、試走会2に向けて調整していたので、それに変更お願いします。

2022-09-01 03:16 UTC, KakinokiKanta commented on camera_system/return_after_setup.py
> +            command_list += "DS,90,-70\n"  # ToDo: 仮のパラメータ
```suggestion
            command_list += "DS,100,-40\n"  # ブロック置き場まで直進(後退)
```

2022-09-01 03:16 UTC, KakinokiKanta commented on camera_system/return_after_setup.py
> +            command_list += "DL,80,0,-60,0.1,0.08,0.08\n"  # ToDo: 仮のパラメータ
```suggestion
            command_list += "DS,50,-40\n"  # 黒を認識するための後退
            command_list += "DL,50,0,-40,0.1,0.08,0.08\n"  # 中点までライントレース
```

2022-09-01 15:49 UTC, kodama0720 approved these changes
LGTM!

2022-09-01 16:16 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/179682)

2022-09-02 00:47 UTC, KakinokiKanta approved these changes
LGTM！

2022-09-02 06:22 UTC, kawanoichi approved these changes
レビュー遅くなり申し訳ありません。大丈夫だと思います
LGTM！

2022-09-02 08:02 UTC, merged