close #31 運搬ブロック決定の実装
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #37
Opened 2022-09-07 12:59 UTC by mutotaka0426

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点

- ゲームエリア情報の仕様を少し変更
  - ゲームエリア情報としてColorクラス(Enum)のvalueを保持しており扱いづらかったため，Colorを格納するように変更
  - それに伴い，一部の変数名を変更
  - Nodeクラスの各インスタンスのゲッターを追加
  - 交点を表す変数名をintersectionに変更
- 次に運搬するブロックを決定するBlockSelectorクラスを追加

## 動作テスト

CIテストをもって動作確認とする

2022-09-08 08:49 UTC, Takahiro55555 reviewed
一点だけ気になる点があったためコメントしました。
その他は問題ないと思います。

2022-09-08 08:49 UTC, Takahiro55555 commented on camera_system/block_selector.py
> +        return cand_nodes[0]
`cand_nodes`の要素数が0になることはあり得ないという認識で大丈夫？

2022-09-08 17:42 UTC, mutotaka0426 commented on camera_system/block_selector.py
> +        return cand_nodes[0]
ありえない想定だけど，保証はされてないかも
25行目の処理については必ずリストが返ってくる前提だとして，優先順位1と優先順位3でもリストが空にならないことを保証した方がいいかな？
優先順位2の最後の処理（43~44行目）みたいな

2022-09-11 14:07 UTC, Takahiro55555 commented on camera_system/block_selector.py
> +        return cand_nodes[0]
>25行目の処理については必ずリストが返ってくる前提だとして

空のリストが返ってくることが無いならこのままで大丈夫だと思います。
（もしかして、空のリストが返ってくる＝ゲーム終了て感じ？）

>優先順位1と優先順位3でもリストが空にならないことを保証した方がいいかな？

優先順位1と優先順位3は処理を見た感じ、`cand_nodes`が空になることは無いように見えたけど、もしかして空になる可能性がある？

2022-09-11 19:04 UTC, mutotaka0426 commented on camera_system/block_selector.py
> +        return cand_nodes[0]
> 空のリストが返ってくることが無いならこのままで大丈夫だと思います。
> （もしかして、空のリストが返ってくる＝ゲーム終了て感じ？）

そうだね．リストが空になってる状況ならそもそもこの関数は呼び出されない筈

> 優先順位1と優先順位3は処理を見た感じ、cand_nodesが空になることは無いように見えたけど、もしかして空になる可能性がある？

空になる可能性なかったわ

2022-09-12 05:23 UTC, miyashita64 reviewed
運搬ブロック決定はいいと思います。
コメントアウトしていた部分だけ気になりました。

2022-09-12 05:23 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +    #    exit(0)
消し忘れですか？

2022-09-12 14:38 UTC, kawanoichi requested changes
変数名についてです。
end から bonus に変更する場合、camera_coordinate_calibrator.py の方も変更をお願いします。

2022-09-12 14:44 UTC, mutotaka0426 commented
> 変数名についてです。 end から bonus に変更する場合、camera_coordinate_calibrator.py の方も変更をお願いします。

camera_coordinate_calibratorのendo_pointは端点座標って意味だけど，game_area_infoのbonus_colorはボーナスブロックの色って意味だから，これじゃダメかな？

ボーナスブロックの色は座標とかじゃなくて，何色がダブルアップになるかってかんじだから合わせなくていいのかなって思ったんだけどどうですか？

2022-09-12 15:29 UTC, kawanoichi requested changes
変数名納得です！！
コメントの書き方についてと、宮下君のコメントしている場所がコメントの外し忘れであれば、他は大丈夫だと思います。

2022-09-12 15:35 UTC, kawanoichi requested changes

2022-09-12 15:35 UTC, kawanoichi commented on camera_system/block_selector.py
> +            # 最も小さい(ブロック→設置先)のマンハッタン距離を求める
個人的に（）の使い方に違和感があります。
```suggestion
            # 最も小さいマンハッタン距離(ブロック→設置先)を求める
```
もしくは
```suggestion
            # 最も小さいマンハッタン距離を求める(ブロック→設置先)
```
はいかがでしょうか？

2022-09-13 15:57 UTC, KakinokiKanta approved these changes
LGTM!!

2022-09-14 12:22 UTC, kawanoichi commented on camera_system/block_selector.py
> +        if(len(cand_nodes) > 1):  # 候補が複数ある場合
if 文()で囲むのは何か処理が変わるのでしょうか？

2022-09-14 13:32 UTC, miyashita64 approved these changes
LGTM!!

2022-09-14 13:55 UTC, mutotaka0426 commented on camera_system/block_selector.py
> +        if(len(cand_nodes) > 1):  # 候補が複数ある場合
pythonのif文の括弧は任意らしいから，書かなくてもいいみたい
ていうか統一性とるために書かない方がいいね

けします

2022-09-14 15:46 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-09-14 17:30 UTC, kawanoichi approved these changes
![139268](https://user-images.githubusercontent.com/96767490/190222922-85bc54e2-8332-4eb6-b9f2-77a22653b5c2.gif)

2022-09-15 07:15 UTC, merged