close #29 #35 最適動作探索クラスを追加
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #41
Opened 2022-09-11 00:11 UTC by miyashita64

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
- 最適動作探索クラスを追加
- ゲームエリア情報クラスでDirection.valueではなくDirectionを返すよう変更
- ゲームエリア情報クラスにブロックがある座標のリストを取得する処理を追加

## 動作テスト

### 実験方法
最適動作探索で求めた動作を可視化し、妥当かを確認する。

### 実験データ
- 青文字はマップの更新
- 動作変換を代替で行っており、方向転換を考慮していないため、成功率が若干低い縦横移動より斜め移動が優先される

#### 検証１
![image](https://user-images.githubusercontent.com/83441177/189505628-d978ad99-5dd2-40a6-ae80-9f54b303e6aa.png)

#### 検証2
![image](https://user-images.githubusercontent.com/83441177/189505987-33e71f89-3ce9-4fb5-89a5-3a6ea52e6853.png)

### 実験結果
現時点のコスト換算で妥当な動作を探索できた。
8ブロックの取得(パターン)と設置(最大3パターン)について1秒台で探索できた。

### 添付資料

2022-09-14 07:42 UTC, mutotaka0426 requested changes
とりあえずカプセル化してないところだけ気になったので指摘してます
見当違いなこと言ってたらすみません

2022-09-14 07:42 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +    def predict_cost(cls, start_robot: Robot, goal_coord: Coordinate) -> int:
この関数ってクラスの外から使わないならプライベートにした方がよくない？
```suggestion
    @classmethod
    def __predict_cost(cls, start_robot: Robot, goal_coord: Coordinate) -> int:
```

2022-09-14 07:42 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +    def next_robots(cls, current_robot: Robot, goal_coord: Coordinate, is_set_motion: bool) -> List[Robot]:  # noqa
ここも
```suggestion
    def __next_robots(cls, current_robot: Robot, goal_coord: Coordinate, is_set_motion: bool) -> List[Robot]:  # noqa
```

2022-09-14 07:42 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +    def robot_hash(cls, robot: Robot) -> int:
ここも
```suggestion
    def __robot_hash(cls, robot: Robot) -> int:
```

2022-09-14 15:38 UTC, mutotaka0426 requested changes
指摘もあるけど，いくつかは疑問みたいな感じです
対応よろしくお願いします。

2022-09-14 15:38 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +        is_set_motion = goal_node.node_type != NodeType.BLOCK.value
[ticket-31](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/pull/37)の方でNodeTypeをvalueでセットしないようにしたからここのvalueはいらないと思う

ticket-31と統合してからマージするなら，どのみちコンフリクトが起こるかテストが通らなくなるから，あとでもいいけど

2022-09-14 15:38 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +            min_cost_transition = transition_table[open.pop(0)]
min_cost_transitionは最小の移動コストみたいな意味？
だとしたらmin_transition_costの方が適当じゃない？

コメントでは推定コストが最小ってあるけど，transitionは推定？

2022-09-14 15:38 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +        # ToDo: エッジを保持する
[ticket-32](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/pull/42)でエッジはRobotが保持して，次の走行体の計算の中でエッジがセットされるようにしてるから，一番最初のRobotのエッジだけセットしてくれれば多分大丈夫だと思う

つまり，ここでは特にセットする必要はないかな？
こいつを呼び出す側が最初のロボットの状態と最後のロボットの状態を保持しておけばいい？

2022-09-14 15:38 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +        transition_table = {
座標と角度で求めたハッシュ値で管理してるからロボット同じ状態になっても対応できるのか
いいね！頭いい！

2022-09-14 15:38 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +                      "motions": CompositeGameMotion(),                         # 開始時からの動作群
`game_motions`の方がシステム全体で統一取れてていいと思うけど，冗長かな？

2022-09-14 15:38 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +                motion = MotionConverterMock.convert(min_cost_transition["robot"], robot)
ここを見ただけで遷移してることを見てわかるように，第二引数はnextが入ってる方がいいと思う．ので，65行目は`for next_robot in next_robots`かなぁ．
できれば第一引数もcurrent_robotとかnow_robotとかの方がいいと思う．
`現在→次`って変数名の方が説明的でよくない？
だとすると`min_cost_transition`自体を変えるか，ここだけのために一時変数をよういするかだけどけ，まぁ納得いかなったら第一引数はいいや

あと，ここもgame_motionの方がいいと思う
```suggestion
                game_motion = MotionConverterMock.convert(current_robot, next_robot)
```

2022-09-14 15:38 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +                    transition_table[hash] = transition
transition_tableがcloseリストの管理も兼ねてるって認識で大丈夫？
ここは，openリストの更新とcloseリストの更新をやってるってことでいい？

openリストの更新の場合，89行目の`open.append(hash)`したら重複しない？

2022-09-14 15:38 UTC, mutotaka0426 commented on tests/test_optimal_motion_searcher.py
> +                    for node_y in [0, 6]:
設置先ノードを表してるのか？
分かりづらいから，素直に設置ノード6つ用意したほうがいいと思う

2022-09-14 15:38 UTC, mutotaka0426 commented on tests/test_optimal_motion_searcher.py
> +                            redirect.close()
テストケース全体の意図が理解できなかった
標準出力を無効化して？とりあえず全パターンで回してるって感じ？

2022-09-14 15:38 UTC, mutotaka0426 commented on tests/test_optimal_motion_searcher.py
> +            for robot_y in robot_coord_elm:
(2,2)と(2,4)と(4,2)と(4,4)をスタートにしてる？
ここも4つのCoordinateを用意したほうがいいと思う

2022-09-14 15:51 UTC, miyashita64 commented on camera_system/optimal_motion_searcher.py
> +            min_cost_transition = transition_table[open.pop(0)]
transitionは、遷移状態？みたいな意味合いで名前を付けていて、{走行体、開始状態から走行体に遷移するためのゲーム動作群、推定コスト、走行体の推移}のことです。
ここでは、最小の推定コストを持つ遷移状態なので、min_cost_transitionとしていました。
命名というよりコメントが不適切でした。すみません。

開始状態から直前の状態までの実コスト + 現在の状態からゴールまでの予測コスト = 推定コスト
と考えていました。コメントに追記します。

2022-09-14 16:27 UTC, miyashita64 commented on camera_system/optimal_motion_searcher.py
> +                    transition_table[hash] = transition
> transition_tableがcloseリストの管理も兼ねてるって認識で大丈夫？
> ここは，openリストの更新とcloseリストの更新をやってるってことでいい？

役割としてはそうです。

> openリストの更新の場合，89行目の`open.append(hash)`したら重複しない？
よりコストが低い動作群が見つかった場合、再度探索する必要があるので、同じハッシュ値がopenに入ることはあり得ます。

普通の経路探索なら、
経路 A->B->C->D->E が探索済みで、
A->B->C よりコストが低い A->X->C が見つかった場合、
A->X->C->D->E とすることができますが、

現状、ゲーム動作群 A->B->C->D->E から C->D->E を切り出して
A->X->C につなげることが困難(実装が複雑になりそう)なので、C以降の動作群は再度探索するようにしました。

2022-09-14 16:38 UTC, miyashita64 commented on tests/test_optimal_motion_searcher.py
> +                            redirect.close()
> 標準出力を無効化して？とりあえず全パターンで回してるって感じ？
そうです。
検証用に大量にprintしていたので、それを無効化して、探索を実行できるか確認するために回していました。

2022-09-15 01:25 UTC, mutotaka0426 commented on camera_system/optimal_motion_searcher.py
> +                    transition_table[hash] = transition
なるほど
まぁこれでも動きはするだろうからいいか

2022-09-15 03:19 UTC, kodama0720 reviewed
レビューが遅くなり申し訳ありません
処理は見た感じ良いと思いました

2022-09-15 03:20 UTC, kodama0720 commented on camera_system/optimal_motion_searcher.py
> +        open = [cls.__robot_hash(start_robot)]
変数名がopenは分かりづらいと思いました

2022-09-15 04:02 UTC, mutotaka0426 approved these changes
テストもいい感じたと思う！
お疲れ様！
![LGTM](https://image.lgtmoon.dev/85055)

2022-09-15 04:56 UTC, miyashita64 commented on camera_system/optimal_motion_searcher.py
> +        open = [cls.__robot_hash(start_robot)]
`open_hashs`なら大丈夫？

2022-09-16 00:42 UTC, kodama0720 approved these changes
LGTM!

2022-09-16 08:26 UTC, kawanoichi approved these changes
![80376](https://user-images.githubusercontent.com/96767490/190592932-fdfc73e8-6551-4774-ad53-952816b3b1de.jpg)

2022-09-17 06:44 UTC, merged