close #32 動作変換の実装
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #42
Opened 2022-09-11 22:45 UTC by mutotaka0426

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- ゲームエリア情報の仕様を少し変更
  - 交点マーカーの色を保持するリスト`intersection_list`を追加
  - CameraCalibrator.make_game_area_info()に，`intersection_list`をセットする処理を追加
  - あとは[ticket-29](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/pull/41)や[ticket-31](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/pull/37)と同様
- 交点に向かう系のゲーム動作で，交点の色を文字列で指定していたところを，Color型で指定するように変更
- Robotクラスがエッジを保持するように拡張
- 現在の走行体と次の走行体からゲーム動作を生成するGameMotionConverterクラスを追加

## 動作テスト

unittestをもって動作確認とする．

### 添付資料

- [ゲーム動作における調整動作の有無について · KatLab-MiyazakiUniv/etrobocon2022-camera-system Wiki](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/wiki/%E3%82%B2%E3%83%BC%E3%83%A0%E5%8B%95%E4%BD%9C%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E8%AA%BF%E6%95%B4%E5%8B%95%E4%BD%9C%E3%81%AE%E6%9C%89%E7%84%A1%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

2022-09-14 06:37 UTC, kawanoichi commented on camera_system/game_area_info.py
> +            if min_direction_value < robot.direct.value < max_direction_value:
```suggestion
            if min_direction_value < robot.direct.value and robot.direct.value < max_direction_value:
```
python は and で分けないといけなかったと思います。

2022-09-14 06:50 UTC, kawanoichi commented on camera_system/game_motion_converter.py
> +        if set(direct_list) & set(no_rotate_list) == set():  # 反時計回りする時に回頭禁止方向に当たらない場合(同じ方位がない場合)
理科不足かもしれませんが気になったのでコメント失礼します。
185行目と193行目の条件式どちらとも当てはまらない状況は生まれないのでしょうか？
当てはまらない場合にclockwise_angleの初期値(360)を返してしまっても大丈夫ですか？

2022-09-14 12:11 UTC, miyashita64 approved these changes
LGTM!!

@kawanoichi の指摘以外、特に引っかかるところはありませんでした。

2022-09-14 13:27 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +        if set(direct_list) & set(no_rotate_list) == set():  # 反時計回りする時に回頭禁止方向に当たらない場合(同じ方位がない場合)
目的の方向まで向けない場合は多分`GameMotionConverter.convert_game_motion()`は呼ばれないかな？つまり，必ずどっちかは360未満になるはず

@miyashita64 と @KakinokiKanta が作ってる[最適動作探索](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/pull/41)がこれを呼び出すんだけど，最適動産探索の方で目的の方向に向けない`次の走行体`は除外してるはず？

確かにこのファイルだけ見たらどっちも当てはまらないパターンがあるように思えるからコメントを追記してもいいんだけど，どうコメントしたものか...

2022-09-14 13:34 UTC, kawanoichi commented on camera_system/game_motion_converter.py
> +        if set(direct_list) & set(no_rotate_list) == set():  # 反時計回りする時に回頭禁止方向に当たらない場合(同じ方位がない場合)
エラー文を書かないのは動作を止めたくないからですか？

2022-09-14 15:46 UTC, KakinokiKanta requested changes
細かいこと1点だけ指摘しているので変更お願いします。

2022-09-14 15:46 UTC, KakinokiKanta commented on camera_system/camera_calibrator.py
>          Args:
is_left_courseについてもArgsにコメント追記お願いします。

2022-09-14 23:12 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +        if set(direct_list) & set(no_rotate_list) == set():  # 反時計回りする時に回頭禁止方向に当たらない場合(同じ方位がない場合)
それは特に考えてないけど
エラー文書くか

2022-09-15 06:43 UTC, KakinokiKanta approved these changes
LGTM!

2022-09-15 10:09 UTC, kawanoichi approved these changes
![181426](https://user-images.githubusercontent.com/96767490/190377468-f67d19f7-5917-4c09-be72-d15b8b8d5c62.jpg)

2022-09-15 10:26 UTC, merged