close #36 ボーナスブロック設置動作の調整
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #43
Opened 2022-09-12 02:30 UTC by kodama0720

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
- ボーナスブロック設置動作のコマンドファイルを作成した

## 動作テスト

### 実験方法
- ボーナスブロックの設置⇒復帰⇒回頭⇒ライントレースまでを20回ずつ行う

### 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

### 実験結果
- East: 調整中 ほぼ毎回同じ位置でコースを外れる（動画参照）
- South: 調整中 5割未満
- West:  8割
- North: 約7割(仮) 再度確認

### 添付資料
- East 黄色交点上の直進で左にそれる（コースの影響？）

https://user-images.githubusercontent.com/83354922/189563362-2210c9a8-127a-4c5e-8734-22419648d69a.MOV

2022-09-14 15:45 UTC, mutotaka0426 commented
一番最初の動画のやつ，設置した後の後退の時左エッジになってる？（進行方向に対して右エッジ？）

2022-09-14 15:53 UTC, mutotaka0426 requested changes
動画見た感じは良さそう！
ただToDoのところだけ気になったので回答よろしくお願いします

2022-09-14 15:53 UTC, mutotaka0426 commented on camera_system/datafiles/LeftBonusEast.csv
> +EC,left,[設置後処理]右エッジに変更(後退用) :ToDo
エッジは前(13行目)と変わってないみたいだけど，このコマンドを入れる意図は？
というか，他のファイルにもあるけどこのToDoは何？
BonusNorth.csvにはToDoはないみたいだけど

2022-09-14 16:42 UTC, KakinokiKanta reviewed
いくつか質問なんですけど、
- ボーナスブロックの設置はどれも中点に設置しているという認識で問題ないですか？
- SLの時間設定が結構バラバラだと感じたのですが、何か基準とかあるのでしょうか？（何か基準を基に設定しているなら、他の動作にも流用できそうだと感じたため）
- 動画を見た感じ、端点からゲームエリアに侵入する際に外側のエッジに乗るようにしたみたいですけど、ブロックがぶつかってしまう問題は無くなりましたか？

2022-09-14 16:48 UTC, kawanoichi commented on camera_system/datafiles/LeftBonusEast.csv
> +EC,left,[設置後処理]右エッジに変更(後退用) :ToDo
明日ミーティングでどうすべきか相談するつもりですが、本来右エッジに変更するために```EC,right,```にしなければならないのですが、スラックでも話したように右エッジでの後退ライントレースをする場合```EC,left,```にしなければいけませんでした。

2022-09-14 17:20 UTC, kawanoichi commented
@KakinokiKanta への回答
・ボーナスブロックは中点に設置することになりました。
・調整の際に試行錯誤していたらこうなってしまいました。すみません。おそらく200に統一して問題ないかと思います。
明日のミーティングまでに統一しても大丈夫そうか確認します。
・調整を行っている人はわかると思いますが、時々走行体が元気になり勢い強い時があります。そのときブロックの衝突は発生します。ですがそこまで頻度が高いわけはないと思います。

2022-09-15 07:40 UTC, miyashita64 approved these changes
LGTM!!

2022-09-15 09:29 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/181405)

2022-09-15 10:03 UTC, sap2368 approved these changes
LGTM!!

2022-09-15 10:04 UTC, merged