close #47 後退ライントレース修正に合わせたコマンドファイルの修正
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #48
Opened 2022-09-20 08:28 UTC by KakinokiKanta

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
- 後退ライントレース修正に合わせたコマンドファイルの修正

### 添付資料

2022-09-21 09:20 UTC, kodama0720 requested changes

2022-09-21 09:20 UTC, kodama0720 commented on camera_system/datafiles/SouthBonusLeft.csv
> +EC,right,[設置後処理]後退用右エッジに変更
上でrightにしてるし要らない？
いや、leftが正しいのかな？

2022-09-21 09:20 UTC, kodama0720 commented on camera_system/datafiles/SouthBonusRight.csv
> +EC,left,[設置後処理]後退用左エッジに変更
ここも

2022-09-21 15:57 UTC, KakinokiKanta commented on camera_system/datafiles/SouthBonusLeft.csv
> +EC,right,[設置後処理]後退用右エッジに変更
Eastとかもエッジ変更の必要ないですか？動画見てエッジの確認はしたんですけど...
Southは上でrightにしてるの見落としてました。

2022-09-21 17:42 UTC, kawanoichi approved these changes
![135272](https://user-images.githubusercontent.com/96767490/191574112-d4f0541a-6c20-40d0-886b-b0c0a88f31be.png)

2022-09-21 20:38 UTC, sugaken0528 approved these changes
LGTM

2022-09-22 02:18 UTC, kodama0720 commented on camera_system/datafiles/SouthBonusLeft.csv
> +EC,right,[設置後処理]後退用右エッジに変更
元がそうなってるなら下手に変えない方がいいか

2022-09-22 02:19 UTC, kodama0720 approved these changes
LGTM!

2022-09-22 04:27 UTC, merged