close #46 回頭のパラメータをブロックの有無によって変える
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #49
Opened 2022-09-20 18:44 UTC by mutotaka0426

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- 各ゲーム動作のコンストラクタの引数に，ブロックを持っているかどうかを判定するフラグを追加
- 各ゲーム動作の親クラスであるGameMotionに，指定角度に対して実際にセットする角度とその動作時間のテーブルを追加
- このテーブルとPWM値は，ブロックの有無によって変化し，これらを用いて各ゲーム動作内の回頭のパラメータを決定する
- 上記の拡張に伴い，最適動作探索クラスと動作変換クラスでブロックの有無を判定するフラグを扱えるように拡張
## 動作テスト
変更前と同様にテストをパスしていることが確認できた．

2022-09-21 09:13 UTC, kodama0720 requested changes
細かい修正だけお願いします

2022-09-21 09:13 UTC, kodama0720 commented on camera_system/block_to_intersection.py
> +            self.__setting_angle = GameMotion.ROTATION_BLOCK_TABLE[abs(angle)]["angle"]
他の変数に合わせて__rotation_angle？

2022-09-21 09:13 UTC, kodama0720 commented on camera_system/game_motion.py
> +        ROTATION_TIME__NO_BLOCK: ブロックを保持していない時の回頭のパラメータ(45度単位で0~360度)
```suggestion
        ROTATION_BLOCK_TABLE: ブロックを保持した時の回頭のパラメータ(45度単位で0~360度)
        ROTATION_NO_BLOCK_TABLE: ブロックを保持していない時の回頭のパラメータ(45度単位で0~360度)
```

2022-09-21 09:56 UTC, mutotaka0426 commented on camera_system/block_to_middle.py
> +            self.__rotation_pwm = GameMotion.ROTATION_BLOCK_PWM
@sugaken0528 @kodama0720 @sap2368 @kawanoichi 
回頭角度にかかわらずPWM値は同じだろって思ってこういう実装にしたけど，もしかして回頭角度によってPWM値も変えた方がいい？
だとしたら`GameMotion.ROTATION_BLOCK_TABLE`にPWMの項目を追加するけど

2022-09-21 10:49 UTC, kodama0720 commented on camera_system/block_to_middle.py
> +            self.__rotation_pwm = GameMotion.ROTATION_BLOCK_PWM
個人的には同じでいいんじゃないかと思います

2022-09-21 18:11 UTC, KakinokiKanta requested changes
細かい修正だけお願いします

2022-09-21 18:11 UTC, KakinokiKanta commented on camera_system/game_motion_converter.py
>              GameAreaInfo: ゲーム動作
```suggestion
            GameMotion: ゲーム動作
```

2022-09-21 18:18 UTC, kawanoichi commented on camera_system/block_to_middle.py
> +            self.__rotation_pwm = GameMotion.ROTATION_BLOCK_PWM
![image](https://user-images.githubusercontent.com/96767490/191578851-62255f72-2655-4ec0-89d7-8c0a59951025.png)

今回行った布と紙の差の検証でpwm80の場合、回頭角度135度以上でブロックを離してしまう可能性があることが分かりました。かし、今までの調整でpwm70(ブロック有)は今まで回頭できずに止まってしまう可能性があることも分かっています。
個人的には止まってしまうよりかはブロックを離してしまう方がマシな気がします。そうなった場合pwmは80で統一できると思うので回頭角度によるpwm値の変更は僕も必要ないかと思います。

2022-09-21 20:56 UTC, sugaken0528 commented on camera_system/block_to_middle.py
> +            self.__rotation_pwm = GameMotion.ROTATION_BLOCK_PWM
同じでいいと思うます

2022-09-22 00:32 UTC, kawanoichi requested changes
よろしくお願いします

2022-09-22 00:32 UTC, kawanoichi commented on camera_system/block_to_intersection.py
> +        self.__clockwise = "clockwise" if angle > 0 else "anticlockwise"
```self.__clockwise = "anticlockwise" ```はおかしい気がするので
```suggestion
        self.__direct_rotation = "clockwise" if angle > 0 else "anticlockwise"
```
とかの方がいい気がします。

2022-09-22 00:32 UTC, kawanoichi commented on camera_system/block_to_intersection.py
>          self.__success_rate = 1.0
```
        expected_color = [Color.BLUE, Color.GREEN, Color.YELLOW, Color.RED]
        # 交点の色以外を指定された場合エラーを出す
        if target_color not in expected_color:
            raise ValueError('"%s" is an Unexpected Color' % target_color.name)
```
を先に行うべきかと思います。

2022-09-22 00:32 UTC, kawanoichi commented on camera_system/block_to_intersection.py
> +        if self.__setting_angle != 0:  # 回頭角度が0の場合はコマンドは生成しない
```suggestion
        if self.__setting_angle != 0:  # 回頭角度が0の場合は回頭のコマンドを生成しない
```

2022-09-22 00:32 UTC, kawanoichi commented on camera_system/intersection_to_block.py
>          # 最後の45度は2回目の回頭で実行するため，angleを2つに分ける
```
        # 縦調整と斜め調整を両方実行することはない
        if vertical_flag and diagonal_flag:
            raise ValueError('Combining Vertical and Diagonal Adjustments is an Unexpected Motion')
```
ここも引数についてなので最初に行うべきだと思います。

2022-09-22 00:32 UTC, kawanoichi commented on camera_system/intersection_to_block.py
>          if self.__first_angle != 0:  # 回頭角度が0の場合はコマンドは生成しない
```suggestion
        if self.__first_angle != 0:  # 回頭角度が0の場合は回頭のコマンドを生成しない
```

2022-09-22 00:32 UTC, kawanoichi commented on camera_system/intersection_to_block.py
>          if self.__second_angle != 0:  # 回頭角度が0の場合はコマンドは生成しない
ここもお願いします。

2022-09-22 02:59 UTC, mutotaka0426 commented on camera_system/block_to_intersection.py
>          self.__success_rate = 1.0
何で？
クラス内で実際に使うのは`self.__target_color`だから，セットし終わった後に検査すべきじゃないかなって思うんだけど

2022-09-22 03:20 UTC, miyashita64 requested changes
遅くなってすみません。
変数名の対応をお願いします。

2022-09-22 03:20 UTC, miyashita64 commented on camera_system/block_to_intersection.py
> +    def __init__(self, angle: int, target_color: Color, have_block: bool) -> None:
`have_block` より `is_have_block` の方がbool値であることが明示的でいいと思います

2022-09-22 03:20 UTC, miyashita64 commented on camera_system/game_motion_converter.py
> +        have_block = is_set_motion  # ブロックを保持しているか(設置動作であるか)
同じく `is_have_block`の方がいいと思います

2022-09-22 03:57 UTC, miyashita64 approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/128637)

2022-09-22 04:21 UTC, kodama0720 approved these changes
LGTM!

2022-09-22 04:29 UTC, KakinokiKanta approved these changes
LGTM!!

2022-09-22 07:38 UTC, kawanoichi approved these changes
![101076](https://user-images.githubusercontent.com/96767490/191686793-31ffb181-ecc5-4fea-8e08-89142fcaa559.jpg)

2022-09-22 07:42 UTC, merged