close #44 運搬動作を決定する
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #50
Opened 2022-09-21 07:45 UTC by miyashita64

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
- 1つのブロックの運搬動作を決定するGameMotionDeciderクラスを追加
- 全カラーブロックについて運搬動作決定を呼び出すGamePlannerクラスを追加

## 動作テスト

### 実験方法
`py game_planner.py`で探索した情報を可視化し確認する。

### 実験データ
![image](https://user-images.githubusercontent.com/83441177/191444814-60ad3769-e07d-43c4-b65a-e44d3760ad47.png)

### 実験結果
`py game_planner.py` で実行した場合は、正常に動いているように見える。
しかし、unittestで`__main__`と同様の処理を実行しても、テストケースの場合ブロックIDが3のブロックを見つけることができずにテストが失敗する。

### 添付資料

2022-09-22 02:05 UTC, kodama0720 reviewed
大体良いと思いました
一点だけ質問です

2022-09-22 02:05 UTC, kodama0720 commented on camera_system/optimal_motion_searcher.py
> +            GameAreaInfo.move_block(goal_node.block_id, on_block_node)
なんでゲームエリア情報を元に戻してるんだっけ？

2022-09-22 03:51 UTC, miyashita64 commented on camera_system/optimal_motion_searcher.py
> +            GameAreaInfo.move_block(goal_node.block_id, on_block_node)
最適動作探索の段階では、動作を探索しただけで決定はしていないから。
ただ、一旦更新しないと復帰動作時の回頭禁止方向等に影響が出るので、動かしたことにして探索した後に戻してる。

2022-09-22 04:24 UTC, mutotaka0426 requested changes
取り合えず

2022-09-22 04:24 UTC, mutotaka0426 commented on camera_system/game_area_info.py
> +        if len(on_target_block_node) == 0:
これとは別に`len(on_target_block_node) > 1`の時のエラー（ワーニング？）処理を追加した方がいいと思う
想定としてはあり得ないけど，リストが複数になるってバグは起こりやすそうだし

2022-09-22 04:24 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +            next_robot.edge = "none"  # →ブロック置き場 or ブロック置き場→ の場合はエッジは"none"になる
コメントのミス
```suggestion
            next_robot.edge = "none"  # →ブロック置き場の場合はエッジは"none"になる
```

2022-09-22 04:24 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +        if next_node_type == NodeType.BLOCK:  # 次の地点がブラック置き場の場合
ブラックになってる
```suggestion
        if next_node_type == NodeType.BLOCK:  # 次の地点がブロック置き場の場合
```

2022-09-22 04:24 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +                                     and (225 <= clockwise_angle <= 315))
条件式が間違ってる
```suggestion
            adjust_conditions.append((current_robot.edge == "left")
                                     and (clockwise_angle == 315))
            adjust_conditions.append((current_robot.edge == "right")
                                     and (clockwise_angle == 45))
```

2022-09-22 04:29 UTC, sugaken0528 requested changes
修正お願いします

2022-09-22 04:29 UTC, sugaken0528 commented on camera_system/game_motion_converter.py
> +        if next_node_type == NodeType.BLOCK:  # 次の地点がブラック置き場の場合
```suggestion
        if next_node_type == NodeType.BLOCK:  # 次の地点がブロック置き場の場合
```

2022-09-22 04:29 UTC, sugaken0528 commented on camera_system/game_motion_converter.py
> +            adjustment_flag = True if any(adjust_conditions) else False  # いずれかの条件を満たしたとき調整有
```suggestion
            need_adjustment = True if any(adjust_conditions) else False  # いずれかの条件を満たしたとき調整有
```
の方が適切だと思う

2022-09-26 08:08 UTC, sugaken0528 approved these changes
LGTM

2022-09-26 08:41 UTC, Takahiro55555 commented on camera_system/datafiles/GameAreaLeft.csv
> +RT,45,100,anticlockwise,��_���u���b�N�u����
文字化けしているのですが、パラメータファイル全体での文字コードは統一されているのでしょうか？

2022-09-26 09:04 UTC, kawanoichi commented on camera_system/optimal_motion_searcher.py
> +            target_direction = [Direction.N, Direction.S]
ここあってますか？

2022-09-26 10:07 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/182244)

2022-09-26 10:08 UTC, KakinokiKanta approved these changes
LGTM!!

2022-09-26 10:27 UTC, kawanoichi approved these changes
![120344](https://user-images.githubusercontent.com/96767490/192254373-5577fa5e-0c55-45c0-93ad-a3127e8357fe.jpg)

2022-09-26 10:30 UTC, sap2368 approved these changes
LGTM

2022-09-26 10:30 UTC, merged