close #51 ゲーム動作のパラメータを計測したパラメータに変更する
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #52
Opened 2022-09-26 11:58 UTC by kodama0720

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
- ゲーム動作のパラメータを変更した
- 回頭前後にスリープを追加した

## 動作テスト

### 実験方法

### 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

### 実験結果

### 添付資料

2022-09-26 12:58 UTC, kawanoichi approved these changes
![78768](https://user-images.githubusercontent.com/96767490/192282542-9e065de4-0148-4fe5-b75d-a3a1d19136e2.jpg)

2022-09-26 13:05 UTC, KakinokiKanta approved these changes
LGTM!!

2022-09-26 13:06 UTC, miyashita64 approved these changes
LGTM!!

2022-09-27 00:02 UTC, mutotaka0426 requested changes
回頭前後のスリープの100ms（とコストの0.1と0.2)のところは全部GameMotionに定義する定数（変数）に置き換えたほうがいいと思う

あと，回頭のパラメータの根拠を示すために，プルリクエストに計測結果の表のリンクを張って欲しい．後で見直せるように

2022-09-27 00:02 UTC, mutotaka0426 commented on camera_system/game_motion.py
> +                            225: {"angle": 219, "time": 120},
120秒の説明を入れてほしい
「失敗率の高い角度or想定しない角度」みたいな？

2022-09-27 00:02 UTC, mutotaka0426 commented on camera_system/block_to_intersection.py
> +            command_list += "SL,100\n"
100msは定数みたいな感じで定義してた方がいいと思う
あと回頭の前後にスリープを入れる意図をコメントに書いてほしい
```suggestion
            command_list += "SL,%d\n" % GameMotion.SLEEP_TIME
```

2022-09-27 00:02 UTC, mutotaka0426 commented on camera_system/block_to_intersection.py
> +        # 回頭前後のスリープ時間を足す
```suggestion
        # 回頭している場合，回頭前後のスリープ時間を足す
```

2022-09-27 00:08 UTC, sugaken0528 approved these changes
LGTM

2022-09-27 00:09 UTC, sap2368 approved these changes
LGTM

2022-09-27 01:29 UTC, mutotaka0426 approved these changes
LGTM

2022-09-27 01:30 UTC, merged