Ticket 53
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #54
Opened 2022-09-27 22:09 UTC by kawanoichi

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 9/27の試走時に発生した問題点
ベースエリア(南)が緑と判定されて青色のベースエリアがなくなってしまい、運搬計画ができなかった。
![color_game_course](https://user-images.githubusercontent.com/96767490/192643573-23fdf2b5-e87c-46d9-9eee-218334093a08.png)

## 変更点
各色の数が合わない場合を回避するために最頻値を求めるのではなく、指定したブロックの領域で各色の割合が大きい順に色を割り当てていくような処理に変更した。

### 実験データ
試走時に問題が発生した画像を使用してうまく色が判別できているかを確認した。
![messageImage_1664313425008](https://user-images.githubusercontent.com/96767490/192645554-613cfa88-121e-4171-9eef-ed70dd9ccafd.jpg)
ベースエリア(南)を青と認識することができている。

実機を使って全体的にうまくいくかの確認はまだできてない。

2022-09-28 09:23 UTC, miyashita64 requested changes

2022-09-28 09:23 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +                point[1],
それぞれが何の値かコメントが欲しい

2022-09-28 09:23 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +        for i in range(block_color_list.shape[0]):
```suggestion
        for _ in range(block_color_list.shape[0]):
```

使わない変数は_を使う慣習があるらしい。
使わないことを明示できるので、こだわりがなければ変えてほしいです

2022-09-28 09:23 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +        for i in range(base_color_list.shape[0]):
同じく
```suggestion
        for _ in range(base_color_list.shape[0]):
```

2022-09-28 09:23 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +                base[1],
なんの値が入っているのかコメントが欲しい

2022-09-28 09:23 UTC, miyashita64 commented on camera_system/camera_calibrator.py
> +            # 配列の最大値のインデックスを取得
```suggestion
            # 配列の最大値のインデックス(ブロックのインデックス, 色のインデックス)を取得
```
あってるかわからんけど、何が入っているか書いてほしい

2022-09-28 09:23 UTC, miyashita64 commented on camera_system/color_changer.py
> +        search_area = search_area = search_area[
```suggestion
        search_area = search_area[
```

2022-09-28 09:23 UTC, miyashita64 commented on camera_system/color_changer.py
> +        if not search_area.shape[0]:
```suggestion
        if search_area != []:
```
個人的にこっちの方がわかりやすいです

2022-09-28 10:30 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/182582)

2022-09-28 10:32 UTC, miyashita64 approved these changes
LGTM

2022-09-28 10:35 UTC, KakinokiKanta approved these changes
LGTM!!

2022-09-28 10:49 UTC, Takahiro55555 commented on camera_system/camera_calibrator.py
> +        bonus_color = np.zeros(CameraCalibrator.__BONUS_BLOCK_NUM)
ゼロ埋めリストを生成したいだけなら、以下のような方法も使えます
```suggestion
        block_color_list = [0] * CameraCalibrator.__COLOR_BLOCK_NUM
        base_color_list =  [0] * CameraCalibrator.__BASE_BLOCK_NUM
        bonus_color = [0] * CameraCalibrator.__BONUS_BLOCK_NUM
```

2022-09-29 04:37 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-09-29 05:13 UTC, merged