布用パラメータ
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #63
Opened 2022-10-15 10:30 UTC by kodama0720

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
- ボーナスブロック設置のパラメータファイルを布用に変更した
- ボーナスブロック設置の回頭前後にスリープ100を追加した
## 動作テスト

### 実験方法

### 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

### 実験結果

### 添付資料

2022-10-17 01:34 UTC, mutotaka0426 requested changes
パラメータがあってるか照合出来てないけど，とりあえず気になったところだけ

2022-10-17 01:34 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +DS,12,70,[ボーナスブロック設置]交点(緑)を乗り越える20
数字だけ書くのは流石に雑だからちゃんと書こう
他のところも
```suggestion
DS,12,70,[ボーナスブロック設置]交点(緑)を乗り越える(20mm直進)
```

2022-10-17 01:34 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +
改行が入ってる

2022-10-17 19:31 UTC, mutotaka0426 requested changes
issueがないから分からないんだけど，ゲームエリア攻略のパラメータは変更しなくていいの？検証の表にはあるみたいだけど
とりあえずissue用意してほしい

2022-10-17 20:17 UTC, sugaken0528 requested changes
プルリクとかissueのタイトルをもう少し詳細にしたほうがいいと思う。
このプルリクの場合は「布上におけるボーナスブロック設置のパラメータ検証」みたいなタイトルが適切。

2022-10-18 03:40 UTC, kodama0720 commented
> issueがないから分からないんだけど，ゲームエリア攻略のパラメータは変更しなくていいの？検証の表にはあるみたいだけど とりあえずissue用意してほしい

ゲームエリア攻略は地区大会前に布上のパラメータに合わせていたと思います
紙上のパラメータの方は変更しておきます

2022-10-18 06:22 UTC, sugaken0528 approved these changes
LGTM

2022-10-25 06:46 UTC, mutotaka0426 approved these changes
LGTM

2022-10-25 08:12 UTC, miyashita64 commented
LGTM

2022-10-25 08:14 UTC, miyashita64 approved these changes
LGTM

2022-10-25 08:15 UTC, merged