close #70 ゲームエリア動作の時間と成功率を変更
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #71
Opened 2022-10-28 13:17 UTC by sugaken0528

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- ゲームエリア動作の時間と成功率を計測した値に変更

### 実験データ
https://docs.google.com/spreadsheets/d/1oWvTgxDAb215ZaO_zJrXGAhXXGuTYOjqzEFAh92o0Ec/edit#gid=0
「#70 コスト算出」と「#70 動作時間」のシートを参照

2022-10-28 13:53 UTC, sap2368 approved these changes
LGTM

2022-10-29 16:06 UTC, miyashita64 approved these changes
LGTM!!

2022-10-31 09:05 UTC, kodama0720 approved these changes
LGTM!

2022-10-31 10:12 UTC, mutotaka0426 requested changes
各ゲーム動作についてだけど，検証回数が違う結果を反映させるのっておかしくない？
検証の仕方として全てのゲーム動作が20回に達するまでっていうのはいいと思うけど，母数は揃えた方がいいんじゃない？
母数は多いに越したことはないけど，母数が違うと検証一回当たりの重みが変わる気がするけどどうですか？

2022-10-31 10:46 UTC, sugaken0528 commented
> 各ゲーム動作についてだけど，検証回数が違う結果を反映させるのっておかしくない？ 検証の仕方として全てのゲーム動作が20回に達するまでっていうのはいいと思うけど，母数は揃えた方がいいんじゃない？ 母数は多いに越したことはないけど，母数が違うと検証一回当たりの重みが変わる気がするけどどうですか？

俺は検証回数を減らして精度の信頼性を下げるくらいなら検証回数にばらつきがあってもいいと思うなー

2022-10-31 12:01 UTC, miyashita64 commented
僕は@sugaken0528さんよりです。
特に検証回数が多いものは、検証回数が少ないものを検証するために必要だった動作だと思うので、実際の計画でも選択肢として出てきやすい動作だと思います。出てきやすい動作についての検証はより厳密な方がいいと思います。

2022-10-31 14:58 UTC, mutotaka0426 commented
> 特に検証回数が多いものは、検証回数が少ないものを検証するために必要だった動作だと思うので、実際の計画でも選択肢として出てきやすい動作だと思います。出てきやすい動作についての検証はより厳密な方がいいと思います。

選択肢として出てきやすい動作っていうのは，検証の結果分かることじゃない？前回の検証（？）も込みで考えるっていうならそれもありなのかもしれないけど，1から考えるっていうなら条件は平等であるべきじゃない？

極端な話でいうと，2回中1回成功した50%と，20回中10回成功した50%を同列に語っていいの？っていう意見です

2022-11-01 04:55 UTC, mutotaka0426 approved these changes
LGTM

2022-11-01 04:58 UTC, merged