close #67 角度補正を計画に組み込む
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #73
Opened 2022-10-29 14:19 UTC by miyashita64

## チェックリスト

- [ x ] format(autopep8) している
- [ x ] コーディング規約(pep8)に準じている
- [ x ] チケットの完了条件を満たしている

## 変更点
- 各ゲーム動作を実現するコマンドに角度補正コマンドを追加
- ゲーム動作生成時の引数に角度補正可能かのフラグを追加
- テストを追加

### 添付資料

2022-10-31 05:12 UTC, kodama0720 requested changes
角度補正を組み込む位置についての疑問です。

2022-10-31 05:12 UTC, kodama0720 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +SL,100,スリープ
ここも補正するの？

2022-10-31 05:12 UTC, kodama0720 commented on camera_system/bonus_datafiles/WestBonusLeft.csv
> +SL,100,スリープ
補正を入れるなら「交点(緑)を乗り越える」の前？

2022-10-31 06:26 UTC, miyashita64 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +SL,100,スリープ
計画側と揃えて、各ゲーム動作の方向転換(有無に関わらず)直後に角度補正補正入れてるつもり。
どこにあった方が都合がいいかは正直自信がないから、意見くれるとありがたい。

2022-10-31 06:41 UTC, miyashita64 commented on camera_system/bonus_datafiles/SouthBonusLeft.csv
> +RT,56,70,clockwise,右に70度回頭
指定角度的に70度の回頭だったためコメントを修正しています

2022-10-31 07:24 UTC, mutotaka0426 requested changes
ちょっとまだレビュー途中だけどとりあえず出しておきます

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/block_to_intersection.py
> +            m_time += GameMotion.SLEEP_TIME
回頭も補正もない場合はスリープ時間は足されないんじゃない?
あと同じ条件ってことが分かりやすいように56行目とかと書き方揃えた方がいいかも
```suggestion
        if self.__can_correction or self.__rotation_angle != 0:
            m_time += GameMotion.SLEEP_TIME * 2
        # 方向転換する、かつ、角度補正する場合、スリープが1回増える
        if self.__can_correction and self.__rotation_angle != 0:
            m_time += GameMotion.SLEEP_TIME
```

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/block_to_middle.py
> +            m_time += GameMotion.SLEEP_TIME
ここも

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +XR,60,60,回頭補正
ここって多分東の方向を向いてる状況だよね？だとしたら目標角度は0？
```suggestion
XR,0,60,回頭補正
```

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +SL,100,スリープ
このチケットの話ではないだろうけど30度回頭ってなんだ？
それは置いといてもここは補正っていれられないんじゃなかったっけ？

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +SL,100,スリープ
ここの回頭って2回に分けてやるやつとかだったっけ？
だとしたらこの直前の回頭補正はいらない？

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/game_motion.py
> +    CORRECTION_NO_BLOCK_PWM = 60    # ブロック未保持時の回頭補正に用いるPWM値 TODO: 妥当なPWM値に更新する
Pythonのセオリーが分かんないけど，改行挟まなくていいんじゃない？
```suggestion
    CORRECTION_BLOCK_PWM = 60       # ブロック保持時の回頭補正に用いるPWM値 TODO: 妥当なPWM値に更新する
    CORRECTION_NO_BLOCK_PWM = 60    # ブロック未保持時の回頭補正に用いるPWM値 TODO: 妥当なPWM値に更新する
```

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/intersection_to_block.py
>          if self.__diagonal_flag:
これもget_cost()でスリープ時間を足さないといけないんじゃない？
（126行目くらいの話だけど選択できないからここに書いてます）

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/intersection_to_middle.py
> +            m_time += GameMotion.SLEEP_TIME
ここも

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/middle_to_block.py
> +            m_time += GameMotion.SLEEP_TIME
ここも

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/middle_to_intersection.py
> +            m_time += GameMotion.SLEEP_TIME
ここも

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/middle_to_middle.py
> +            m_time += GameMotion.SLEEP_TIME
ここも

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/return_to_block.py
>          # 調整動作ありの場合，縦調整をセットする
補正が必ず入るから，スリープはその前後で2回固定で入るようになったよね？
つまり回頭の有無で変化するスリープの回数は一回分だけだから，73行目の`* 2`はいらなくなったかな？
（設置後復帰動作は絶対に行う動作分の時間は省略するから，回頭や調整動作の分だけ足してる）
※73行目を選択できないからここに書いてます

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/return_to_intersection.py
>          # 回頭後にエッジが切り替わる場合，エッジ切り替えをセットする
これの78行目も同様

2022-10-31 07:24 UTC, mutotaka0426 commented on camera_system/return_to_middle.py
>          # 回頭後にエッジが切り替わる場合，エッジ切り替えをセットする
これの71行目も

2022-10-31 07:54 UTC, miyashita64 commented on camera_system/bonus_datafiles/WestBonusLeft.csv
> +SL,100,スリープ
本来は、
交差点に乗る→(角度補正)→交点を乗り越える
なんだけど、
「交差点に乗る」と「交点を乗り超える」が一体化してると思って、どっちに入れるか迷ったんだけど、前のほうがよさそう？

2022-10-31 08:59 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +        return True
(0, 4)で北を向いてる時とかはギリギリ補正入れても大丈夫なんだっけ？

2022-10-31 09:02 UTC, kodama0720 commented on camera_system/bonus_datafiles/WestBonusLeft.csv
> +SL,100,スリープ
乗り越えた後だとすでにエッジから外れてそうだから、前の方が良い気がする

2022-10-31 09:16 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +    def __can_correction(self, coord: Coordinate, direct: Direction) -> bool:
名前が変数っぽいし，何より実際の変数と名前が被ってるのは問題だと思う
setとかを付けた方がいいんじゃない
```suggestion
    def __set_can_correction(self, coord: Coordinate, direct: Direction) -> bool:
```

2022-10-31 10:07 UTC, mutotaka0426 reviewed
よくわからないところがあった
`can_adjust_correction`の計算のところだけど間違ってるように見える
例えば`angle == -135`の時は，`-90度回頭→補正1→(縦調整)→-45度回頭→補正2`って感じになると思うけど，この補正1時点での方位が知りたいんだよね？
現在の方位から-90度回頭した時の方位を出すんだと思うけどあってる？

2022-10-31 10:07 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +                                      len(Direction)) % len(Direction)
`sub_direct_num`って既に用意している`angle`じゃダメなの？
`sub_direct_num == 3`ってつまり`abs(angle) == 135`ってことではない？

2022-10-31 10:07 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +                        in_adjustment_direct = Direction((next_direct_num + 3) % len(Direction))
これって何してるの？
最初の回頭直後の方向を出したいってことだよね？

2022-10-31 12:44 UTC, miyashita64 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +SL,100,スリープ
北向きから右に30度の角度なら、北向き判定で大丈夫かと思ったんですが難しいですか？

2022-10-31 12:44 UTC, miyashita64 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +XR,60,60,回頭補正
東を向くのは34行目あたりだと思うので0ではないと思いますが、ここで北から右に60度回頭した状態の場合は60で大丈夫ですか？

2022-10-31 12:52 UTC, miyashita64 commented on camera_system/game_motion_converter.py
> +                                      len(Direction)) % len(Direction)
そういうことですね。
改めてみるとかなり見づらいので書き直します

2022-10-31 12:53 UTC, miyashita64 commented on camera_system/game_motion_converter.py
> +                        in_adjustment_direct = Direction((next_direct_num + 3) % len(Direction))
そうです。ちょっと書き換えます。

2022-10-31 15:08 UTC, miyashita64 commented on camera_system/game_motion_converter.py
> +        return True
![image](https://user-images.githubusercontent.com/96767490/198519155-507b268f-1264-4d47-b160-2213235ab25a.png)

距離的には、(6,2)で東を向いているときに↑の写真の1番手前の77.93が見えるぐらいのはずです。

2022-10-31 16:18 UTC, miyashita64 commented
> `can_adjust_correction`の計算のところだけど間違ってるように見える
> 
> 例えば`angle == -135`の時は，`-90度回頭→補正1→(縦調整)→-45度回頭→補正2`って感じになると思うけど，この補正1時点での方位が知りたいんだよね？
> 
> 現在の方位から-90度回頭した時の方位を出すんだと思うけどあってる？

それでよかったんですが、無駄に侵入時のエッジ等を混ぜて考えてしまってました。修正しました。

2022-11-01 03:00 UTC, kawanoichi commented on camera_system/bonus_datafiles/SouthBonusLeft.csv
>  CL,GREEN,0,70,0.2,0.08,0.08,緑(右上)までライントレース
```suggestion
CL,GREEN,0,70,0.2,0.08,0.08,緑(左上)までライントレース
```
すみません。チケット違いますけど、ここ修正をお願いします

2022-11-01 03:58 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +SL,100,スリープ
いけるのか
じゃあ大丈夫

2022-11-01 04:27 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/180913)

2022-11-01 04:41 UTC, sugaken0528 requested changes

2022-11-01 04:41 UTC, sugaken0528 commented on camera_system/block_to_intersection.py
> +            can_correction: 角度補正を行う場合True
```suggestion
            can_correction: 角度補正が可能な場合True
```

2022-11-01 04:41 UTC, sugaken0528 commented on camera_system/block_to_middle.py
> +            can_correction: 角度補正を行う場合True
同様

2022-11-01 05:01 UTC, kawanoichi approved these changes
![186243](https://user-images.githubusercontent.com/96767490/199162542-57ed0134-aa45-4295-861a-b20fa3fc1e31.png)

2022-11-01 05:14 UTC, sugaken0528 approved these changes
LGTM

2022-11-01 13:41 UTC, kodama0720 approved these changes
LGTM!

2022-11-02 04:31 UTC, mutotaka0426 requested changes
ちょっとだけ引っかかったところがあった
対応よろしく

2022-11-02 04:31 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +        COORD_LENGTH = 125    # 縦横の座標との距離[mm]
座標間の距離ってこと？
なんか説明が理解しづらいかも
隣接座標とかの方が分かりやすくない？

2022-11-02 04:31 UTC, mutotaka0426 commented on camera_system/game_motion_converter.py
> +                continue
352行目のifでTrueを返す前に，これに引っかかったらFalseにならない？
breakじゃダメなの？

2022-11-02 05:03 UTC, kawanoichi requested changes

2022-11-02 05:03 UTC, kawanoichi commented on camera_system/game_motion_converter.py
> +        COORD_LENGTH = 125    # 縦横の座標との距離[mm]
```suggestion
        COORD_LENGTH = 125    # 座標間(縦横)の距離[mm]
```

2022-11-02 05:03 UTC, kawanoichi commented on camera_system/game_motion_converter.py
> +        # リアカメラが移す座標の方向を求める
移す？？？
```suggestion
        # リアカメラが映す座標の方向を求める
```

2022-11-02 07:13 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/167347)

2022-11-02 09:54 UTC, sugaken0528 approved these changes
LGTM

2022-11-02 11:25 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-11-02 14:19 UTC, kawanoichi approved these changes
![186479](https://user-images.githubusercontent.com/96767490/199513662-92262aa6-a97e-4d5f-a4af-f33e0dfb928d.jpg)

2022-11-03 01:02 UTC, merged