close #74 ボーナスブロック設置のコマンドファイル再構成
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #77
Opened 2022-11-06 15:58 UTC by miyashita64

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- ゲームエリア侵入を90度で行うように変更
- 各動作をゲーム動作に準じる形に変更
- コメントの統一(距離直進と回頭は目標値を明記、過剰なコメントの削除)

## 動作テスト

### 実験方法
決定したコマンドファイルでボーナスブロック設置を行った。

### 実験データ
角度補正なし

### 実験結果
角度補正なしで、ボーナスブロックを設置できる場合があることを確認した。

### 添付資料

2022-11-06 19:09 UTC, mutotaka0426 requested changes
まだ全部は追えてないけどとりあえず
角度補正の角度は[ticket-75](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/pull/76)のやつで指摘してます
ブロックの有無に対応したpwm値の変更を指摘したつもりだけど，間違ってないかは確認してほしい

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +SL,100
角度補正入れてもいいんじゃない
入れるって話になってたよね？
ちなみにブロックありの時のPWMが59で，なしの時が47ね
```suggestion
SL,100
XR,0,59
SL,100
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +CS,GREEN,-60,[交点(6,4)→中点(5,4)→交点(4,4) 設置後復帰]
ここから設置後復帰動作と同様の動きをするってことか？
このコメントがあるのはいいとしても，(6, 4)の交点に乗るとかが記載されてる方が見てる人が追いやすくない？

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusRight.csv
> +SL,100
ここも回頭補正？

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusLeft.csv
> +SL,100
ここも

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +SL,100
ここも

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/SouthBonusLeft.csv
> +SL,100
ここも

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/SouthBonusRight.csv
> +SL,100
ここも

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/WestBonusLeft.csv
> +SL,100
ここも

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/WestBonusRight.csv
> +SL,100
ここも

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusLeft.csv
> +XR,0,60
ブロックなしのpwm
```suggestion
XR,0,47
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusRight.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusRight.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusRight.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/EastBonusRight.csv
> +XR,0,60
ブロックなし
```suggestion
XR,0,47
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusLeft.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusLeft.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusLeft.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusLeft.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusLeft.csv
> +XR,0,60
ブロックなし
```suggestion
XR,0,47
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +XR,0,60
ブロックなし
```suggestion
XR,0,47
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/SouthBonusLeft.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/SouthBonusLeft.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/SouthBonusLeft.csv
> +XR,0,60
ブロックなし
```suggestion
XR,0,47
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/SouthBonusRight.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/SouthBonusRight.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/SouthBonusRight.csv
> +XR,0,60
ブロックなし
```suggestion
XR,0,47
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/WestBonusLeft.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/WestBonusLeft.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/WestBonusLeft.csv
> +XR,0,60
ブロックあり
```suggestion
XR,0,59
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/WestBonusLeft.csv
> +XR,0,60
ブロックなし
```suggestion
XR,0,47
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/WestBonusRight.csv
> +XR,0,60
ブロックなし
```suggestion
XR,0,47
```

2022-11-06 19:09 UTC, mutotaka0426 commented on camera_system/datafiles/CarryBonusLeft.csv
> +XR,0,60
ブロックなし
```suggestion
XR,0,47
```

2022-11-07 18:24 UTC, sugaken0528 requested changes
説明or修正お願いします

2022-11-07 18:24 UTC, sugaken0528 commented on camera_system/bonus_datafiles/EastBonusRight.csv
> +XR,0,59,ブロックあり角度補正
回頭の時以外にも角度補正使うんだっけ？
経路計画で生成される動作に合わせるって話あったけど、ここで補正入れる程度なら気にする必要ない？
そもそもここで補正必要ない気もするけど

2022-11-07 18:24 UTC, sugaken0528 commented on camera_system/bonus_datafiles/NorthBonusLeft.csv
> +DS,35,-70
```suggestion
DS,35,-70,60mm後退
```

2022-11-07 18:24 UTC, sugaken0528 commented on camera_system/bonus_datafiles/NorthBonusRight.csv
> +DS,35,-70
```suggestion
DS,35,-70,60mm後退
```

2022-11-07 18:24 UTC, sugaken0528 commented on camera_system/bonus_datafiles/SouthBonusLeft.csv
> +DS,35,-70
```suggestion
DS,35,-70,60mm後退
```

2022-11-07 18:24 UTC, sugaken0528 commented on camera_system/bonus_datafiles/SouthBonusLeft.csv
> +CS,BLUE,-60,交点(4,6)に乗る[交点(4,6)→中点(4,5)→交点(4,4)]
```suggestion
CS,GREEN,-60,交点(4,6)に乗る[交点(4,6)→中点(4,5)→交点(4,4)]
```
緑だよね？

2022-11-07 18:24 UTC, sugaken0528 commented on camera_system/bonus_datafiles/SouthBonusRight.csv
> +DS,35,-70
```suggestion
DS,35,-70,60mm後退
```

2022-11-07 18:24 UTC, sugaken0528 commented on camera_system/bonus_datafiles/SouthBonusRight.csv
> +CS,BLUE,-60,交点(2,6)に乗る[交点(2,6)→中点(2,5)→交点(2,4)]
```suggestion
CS,GREEN,-60,交点(2,6)に乗る[交点(2,6)→中点(2,5)→交点(2,4)]
```
あえてBLUEにしてるなら理由をコメントに書いといて

2022-11-08 00:04 UTC, miyashita64 commented on camera_system/bonus_datafiles/EastBonusRight.csv
> +XR,0,59,ブロックあり角度補正
全ゲーム動作では、
方向転換の回頭（ない場合は省略）
→角度補正
→座標間の移動
の順に行なっていくので、位置的に可能であれば、回頭直後以外でも角度補正は行う形になってます。

パラメータを更新した角度補正を含めた検証はできていないので、必要とは言いれませんが、角度補正直後のライントレースや直進の安定には繋がるんじゃないかと思ってます。

2022-11-08 01:03 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/NorthBonusLeft.csv
> -SL,100
設置の時の回頭には補正を付けないから消したって認識でok？

2022-11-08 01:14 UTC, mutotaka0426 commented on camera_system/bonus_datafiles/SouthBonusLeft.csv
> +RT,56,70,clockwise,右70度回頭(SからE方向に70度)
```suggestion
RT,56,70,clockwise,右70度回頭(SからW方向に70度)
```
かな？

2022-11-08 03:27 UTC, sugaken0528 approved these changes
LGTM

2022-11-08 04:31 UTC, miyashita64 commented on camera_system/bonus_datafiles/NorthBonusLeft.csv
> -SL,100
okです

2022-11-08 06:36 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/129484)

2022-11-08 06:38 UTC, KakinokiKanta approved these changes
LGTM!!

2022-11-08 06:43 UTC, merged