#6 Pythonの環境構築
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #8
Opened 2022-07-03 14:35 UTC by Takahiro55555

## チェックリスト

- [X] autopep8(formatter)を適用している
- [X] pep8(コーディング規約)に準じている
- [X] チケットの完了条件を満たしている

>**Note**
>[Poetry](https://python-poetry.org/docs/)のインストールが必須です。

>**Warning**
>現状、WSL上での使用のみを想定しています。WSL上のPythonからWebカメラのアクセスが難しい場合は、Windows環境向けに修正する予定です。
>また、CI環境は別チケットになる予定です（レビューが重くなりそうだったため）。

## 変更点
- プルリクのテンプレートをカメラシステム用に修正
- Pythonの開発環境(WSL)の設定

## 動作テスト
以下の機能をWSL上の`make`コマンドから利用できることを確認した。
- プログラムの実行
- formatterの実行及びフォーマットの適用
- linterの実行
- 単体テストの実行(unittest)
- カバレッジのCLIからの確認
- カバレッジのブラウザからの確認

![make-exec](https://user-images.githubusercontent.com/31930148/177043001-127fad13-9beb-4eb1-8096-12642c6724fb.PNG)
![coverage-html](https://user-images.githubusercontent.com/31930148/177043006-83d950f0-ca5e-46f4-a3c1-18a0d54258e9.PNG)

## 添付資料
- [[python] プロジェクトのディレクトリ推奨構成 - Qiita](https://qiita.com/flcn-x/items/c866eec8824a3cd70fa8)

2022-07-04 23:54 UTC, mutotaka0426 requested changes
現状俺のpythonの環境構築がうまくいってないみたいで動かして試せてはないけど，コードレビューした感じはよさそう！unittestの採用理由も納得した！

あとは動作には直接関係しないであろう箇所の指摘をしたけど，Python全然わからなくて調べながらレビューしたから，的外れな指摘してるかもしれないです

ディレクトリ名の`camera/`に関してはミーティングのときに全員で決めればいいと思う
参考資料ではプロジェクト名ってあるけど，個人的には`camera/`はあまり直感的ではなく感じる
`modules/`とか`src/`とかでもいいんじゃないかなと思う

2022-07-04 23:54 UTC, mutotaka0426 commented on camera/camera_system.py
> +
pythonのドキュメントコメントについて調べてみたけど，ファイルそのものに対するドキュメントってどう残すのが一般的なのかちょっとわからなかった
Doxygenみたいにしてしまってもいいんではないかと思うんだけどどうでしょう

クラスの説明は欲しいけどそれは9行目とかに挿入するべきなのかな？

```suggestion
"""
@file camera_system.py
@brief カメラシステムモジュール
@author: Takahiro55555
"""


class CameraSystem:
    """カメラシステムクラス
    カメラシステム全体を制御する
    """
```
クラス説明間違ってたらゴメン

2022-07-04 23:54 UTC, mutotaka0426 commented on README.md
>  走行システムのプログラムは[こちら](https://github.com/KatLab-MiyazakiUniv/etrobocon2022)を参照。
走行システムと同様に開発環境を追加してほしい
とりあえず以下が必要かな？
- Python 〇.〇
- unittest（Python標準のテストフレームワーク）
- 〇〇（linter）
- autopep8（formatter）

2022-07-04 23:54 UTC, mutotaka0426 commented on tox.ini
> +max-line-length = 160
160って何を参考に決めてる？
pep8では79~99って書いてあるよ（docstrignは72）

2022-07-04 23:54 UTC, mutotaka0426 commented on camera/str_to_bool.py
> +class StrToBool:
標準ライブラリで同じようなことできるものがあるみたいだけど，あえて作る理由ってあるの？（[参考資料](https://python.civic-apps.com/str-to-bool/)）

2022-07-05 10:50 UTC, Takahiro55555 commented on camera/str_to_bool.py
> +class StrToBool:
`distutils.util.strtobool`の存在は知りませんでした。
なので、このまま採用しようとも思いましたが、[公式ドキュメント](https://docs.python.org/ja/3.10/library/distutils.html)によると、Python3.10.4では非推奨となっているようです。
> [distutils](https://docs.python.org/ja/3/library/distutils.html#module-distutils) は 非推奨で、Python 3.12 での除去が予定されています。 より詳しい情報は [What's New](https://docs.python.org/ja/3/whatsnew/3.10.html#distutils-deprecated) 記事を参照してください。

なので、個人的には残す方向がいいかなと思いますがどうでしょうか？

2022-07-05 10:54 UTC, Takahiro55555 commented on tox.ini
> +max-line-length = 160
160はさすがに長すぎる気がしてきました。

以下の記事を参考に、100に変更しようと思います。

https://news.mynavi.jp/techplus/article/20200602-1047066/

2022-07-05 11:23 UTC, mutotaka0426 commented on camera/str_to_bool.py
> +class StrToBool:
それなら確かに`distutils.util.strtobool`は使わない方がいいですね
残す方向で大丈夫です

2022-07-08 06:12 UTC, mutotaka0426 commented on README.md
> +詳しくは[Wiki](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/wiki/)を参照してください。
プレビュー見ると，ここ改行されてないみたいだよ

2022-07-08 18:59 UTC, Takahiro55555 commented on camera/camera_system.py
> +
Docstringに関しては以下の記事を参考に、GoogleスタイルのDocstringに統一することにしました。
https://qiita.com/11ohina017/items/118b3b42b612e527dc1d

また、作成者名は記述したほうが良いと考え、著者名の部分のみDoxygen形式で記述するようにしてみました。

2022-07-08 19:00 UTC, Takahiro55555 commented on README.md
> +詳しくは[Wiki](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/wiki/)を参照してください。
修正しました。

2022-07-09 16:57 UTC, mutotaka0426 commented
レビューした感じは良さそうなので手元環境で実行確認出来たらapproveだします
ちょっと待っててください

2022-07-10 14:32 UTC, kodama0720 approved these changes
LGTM!
手元で動作確認できました

2022-07-11 14:27 UTC, mutotaka0426 approved these changes
ノートPCで動作確認できました！
![LGTM](https://image.lgtmoon.dev/134176)

2022-07-13 03:14 UTC, miyashita64 approved these changes
LGTM!!
動作確認もできました！

2022-07-13 06:31 UTC, merged