ゲーム動作の調整動作のパラメータ更新
KatLab-MiyazakiUniv/etrobocon2022-camera-system pull request #82
Opened 2022-11-10 16:15 UTC by sap2368

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- 調整動作のパラメータを検証済みのものに更新
- 検証を行えていなかったパラメータに関しては新に検証
## 動作テスト
- 検証済みのパラメータに変更後問題なく動作するかを確認

2022-11-11 09:45 UTC, mutotaka0426 commented
調整動作以外のやつが正しいのか分からないから，検証したやつスプレットシートのどこ見ればいいか，リンク付きで書いてほしい

2022-11-12 14:05 UTC, kodama0720 approved these changes
LGTM!

2022-11-13 03:52 UTC, miyashita64 requested changes
今更ごめん。
block_to_intersectionのパラメータだけ気になったので教えてほしいです。
コメントの指摘については任意で大丈夫です。

2022-11-13 03:52 UTC, miyashita64 commented on camera_system/block_to_intersection.py
> +        command_list += "DS,42,70\n"  # 走行体がエッジに乗るまで直進
[調整動作のパラメータ](https://docs.google.com/spreadsheets/d/1oWvTgxDAb215ZaO_zJrXGAhXXGuTYOjqzEFAh92o0Ec/edit#gid=45421707)的には指定距離42だと、68mm直進になるけどいいんだっけ？
計算上は色認識してから交差点までは16mmのはず。

勘違いならごめんなさい。

2022-11-13 03:52 UTC, miyashita64 commented on camera_system/intersection_to_block.py
> +            command_list += "DS,12,70\n"
```suggestion
            command_list += "DS,12,70,20mm直進(縦調整)\n"
```
コマンドにコメントがあるほうが直前の調整が楽かもしれないです

2022-11-13 03:52 UTC, miyashita64 commented on camera_system/intersection_to_block.py
> +            command_list += "DS,17,70\n"
同様
```suggestion
            command_list += "DS,17,70,30mm直進(斜め調整)\n"
```

2022-11-13 03:52 UTC, miyashita64 commented on camera_system/intersection_to_middle.py
> +            command_list += "DS,12,70\n"
同様
```suggestion
            command_list += "DS,12,70,20mm直進(縦調整)\n"
```

2022-11-13 03:52 UTC, miyashita64 commented on camera_system/middle_to_block.py
> +            command_list += "DS,12,70\n"
同様

2022-11-13 03:52 UTC, miyashita64 commented on camera_system/middle_to_intersection.py
> +        command_list += "DS,12,70\n"  # 交差点まで直進
同様

2022-11-13 05:29 UTC, kawanoichi approved these changes
![115758](https://user-images.githubusercontent.com/96767490/201507350-25b39b94-7af7-4765-9287-6d8805419408.jpg)

2022-11-13 05:53 UTC, miyashita64 approved these changes
LGTM!!

2022-11-13 05:58 UTC, merged